/* eslint-disable @typescript-eslint/no-explicit-any -- public catalog adapters map heterogeneous D1 joins */
import { businesses as fallbackBusinesses, events as fallbackEvents, jobs as fallbackJobs, offers as fallbackOffers, places as fallbackPlaces, restaurants as fallbackRestaurants } from "../data";
import type { PublicBusiness, PublicCatalog, PublicEvent, PublicJob, PublicOffer, PublicPlace, PublicPost, PublicRestaurant } from "../public-types";
import { getRuntimeDb } from "../../db/runtime";
import { normalizeRichText, richTextToPlainText } from "../rich-text";

const published = "(c.status='published' OR (c.status='scheduled' AND datetime(c.scheduled_at)<=datetime(?))) AND c.visibility='public' AND c.deleted_at IS NULL AND c.is_demo=0 AND (c.expires_at IS NULL OR datetime(c.expires_at)>datetime(?))";

export function bucharestDate(now = new Date()) {
  const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/Bucharest", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(now);
  const value = Object.fromEntries(parts.map((part) => [part.type, part.value]));
  return `${value.year}-${value.month}-${value.day}`;
}

export async function loadPublicCatalog(now = new Date()): Promise<PublicCatalog> {
  const nowIso = now.toISOString();
  const today = bucharestDate(now);
  try {
    const db = getRuntimeDb();
    const [eventRows, businessRows, offerRows, restaurantRows, jobRows, placeRows, postRows] = await Promise.all([
      db.prepare(`SELECT c.id content_id,c.entity_id,c.updated_at,(SELECT id FROM media_assets WHERE content_id=c.id AND approval_status='approved' AND media_status='active' ORDER BY created_at DESC LIMIT 1) cover_media_id,e.*,cat.name category_name FROM content_records c JOIN events e ON e.id=c.entity_id LEFT JOIN categories cat ON cat.id=e.category_id WHERE c.type='event' AND ${published} AND ((e.ends_at IS NOT NULL AND datetime(e.ends_at)>datetime(?)) OR (e.ends_at IS NULL AND substr(e.starts_at,1,10)>=?)) ORDER BY datetime(e.starts_at)`).bind(nowIso, nowIso, nowIso, today).all<any>(),
      db.prepare(`SELECT c.id content_id,c.entity_id,c.promoted_tier,c.updated_at,(SELECT id FROM media_assets WHERE content_id=c.id AND approval_status='approved' AND media_status='active' ORDER BY created_at DESC LIMIT 1) cover_media_id,b.*,cat.name category_name FROM content_records c JOIN businesses b ON b.id=c.entity_id LEFT JOIN categories cat ON cat.id=b.category_id WHERE c.type='business' AND ${published} AND b.deleted_at IS NULL ORDER BY c.featured DESC,b.name`).bind(nowIso, nowIso).all<any>(),
      db.prepare(`SELECT c.id content_id,c.entity_id,c.promoted_tier,c.updated_at,(SELECT id FROM media_assets WHERE content_id=c.id AND approval_status='approved' AND media_status='active' ORDER BY created_at DESC LIMIT 1) cover_media_id,o.*,b.name business_name,b.locality,b.address,b.latitude,b.longitude,cat.name category_name FROM content_records c JOIN offers o ON o.id=c.entity_id LEFT JOIN businesses b ON b.id=o.business_id LEFT JOIN categories cat ON cat.id=b.category_id WHERE c.type='offer' AND ${published} AND date(o.starts_at)<=date(?) AND date(o.ends_at)>=date(?) ORDER BY date(o.ends_at)`).bind(nowIso, nowIso, today, today).all<any>(),
      db.prepare(`SELECT c.id content_id,c.entity_id,c.updated_at,(SELECT id FROM media_assets WHERE content_id=c.id AND approval_status='approved' AND media_status='active' ORDER BY created_at DESC LIMIT 1) cover_media_id,r.*,b.locality,b.address,b.latitude,b.longitude,b.phone,dm.soup,dm.main_dish,dm.price menu_price,dm.updated_at menu_updated FROM content_records c JOIN restaurants r ON r.id=c.entity_id LEFT JOIN businesses b ON b.id=r.business_id LEFT JOIN daily_menus dm ON dm.restaurant_id=r.id AND dm.status='published' AND dm.availability='active' AND date(dm.menu_date)=date(?) WHERE c.type='restaurant' AND ${published} GROUP BY c.id ORDER BY r.name`).bind(today, nowIso, nowIso).all<any>(),
      db.prepare(`SELECT c.id content_id,c.entity_id,c.updated_at,(SELECT id FROM media_assets WHERE content_id=c.id AND approval_status='approved' AND media_status='active' ORDER BY created_at DESC LIMIT 1) cover_media_id,j.*,b.address,b.latitude,b.longitude FROM content_records c JOIN jobs j ON j.id=c.entity_id LEFT JOIN businesses b ON b.id=j.business_id WHERE c.type='job' AND ${published} AND (j.deadline IS NULL OR date(j.deadline)>=date(?)) ORDER BY date(j.deadline)`).bind(nowIso, nowIso, today).all<any>(),
      db.prepare(`SELECT c.id content_id,c.entity_id,c.updated_at,(SELECT id FROM media_assets WHERE content_id=c.id AND approval_status='approved' AND media_status='active' ORDER BY created_at DESC LIMIT 1) cover_media_id,p.* FROM content_records c JOIN places p ON p.id=c.entity_id WHERE c.type='place' AND ${published} ORDER BY c.featured DESC,p.id`).bind(nowIso, nowIso).all<any>(),
      db.prepare(`SELECT c.id content_id,c.entity_id,c.updated_at,(SELECT id FROM media_assets WHERE content_id=c.id AND approval_status='approved' AND media_status='active' ORDER BY created_at DESC LIMIT 1) cover_media_id,c.title,c.excerpt,c.slug,p.post_type,p.body,p.locality,p.source_information,cat.name category_name,u.display_name author_name,b.name business_name FROM content_records c JOIN posts p ON p.id=c.entity_id LEFT JOIN categories cat ON cat.id=p.category_id LEFT JOIN users u ON u.id=p.author_user_id LEFT JOIN businesses b ON b.id=p.business_id WHERE c.type IN ('community_post','local_story','article','business_update') AND ${published} ORDER BY datetime(c.published_at) DESC`).bind(nowIso, nowIso).all<any>(),
    ]);
    return { events:eventRows.results.map(mapEvent), businesses:businessRows.results.map(mapBusiness), offers:offerRows.results.map(mapOffer), restaurants:restaurantRows.results.map(mapRestaurant), jobs:jobRows.results.map(mapJob), places:placeRows.results.map(mapPlace), posts:postRows.results.map(mapPost) };
  } catch (error) {
    console.error("public_catalog_fallback", error instanceof Error ? error.message : "unknown");
    return fallbackCatalog(now);
  }
}

function fallbackCatalog(now: Date): PublicCatalog {
  const today = bucharestDate(now);
  return {
    events: fallbackEvents.filter((item) => item.startDate.slice(0, 10) >= today).map((item) => ({ ...item, isDemo:true, isFree:/gratuit|liber/i.test(item.price) })),
    businesses: fallbackBusinesses.map((item) => ({ ...item, isDemo:true })),
    offers: fallbackOffers.map((item) => ({ ...item, isDemo:true, startsAt:"2026-08-01", endsAt:isoFromRomanianDate(item.until) })),
    restaurants: fallbackRestaurants.map((item) => ({ ...item, isDemo:true, delivery:item.services.includes("Livrare"), pickup:item.services.includes("Ridicare") })),
    jobs: fallbackJobs.map((item) => ({ ...item, isDemo:true, salaryDisclosed:!/interviu|negociabil/i.test(item.salary) })),
    places: fallbackPlaces.map((item) => ({ ...item, isDemo:true, locality:"Blaj" })), posts:[],
  };
}

function validDate(value?: string | null) { if (!value || value === "CURRENT_TIMESTAMP") return undefined; const normalized=/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/.test(value)?`${value.replace(" ","T")}Z`:value;return Number.isNaN(new Date(normalized).getTime())?undefined:normalized; }
function date(value:string){const valid=validDate(value);return valid?new Intl.DateTimeFormat("ro-RO",{day:"numeric",month:"long",year:"numeric",timeZone:"Europe/Bucharest"}).format(new Date(valid)):"Dată neconfirmată";}
function time(value:string){const valid=validDate(value);return valid?new Intl.DateTimeFormat("ro-RO",{hour:"2-digit",minute:"2-digit",timeZone:"Europe/Bucharest"}).format(new Date(valid)):"";}
function money(value:number|null|undefined){return value==null?"Preț necomunicat":`${new Intl.NumberFormat("ro-RO").format(value)} lei`;}
function media(row:any,fallback?:string){return row.cover_media_id?`/api/media/${row.cover_media_id}`:fallback;}
function isoFromRomanianDate(value:string){const months:Record<string,string>={ianuarie:"01",februarie:"02",martie:"03",aprilie:"04",mai:"05",iunie:"06",iulie:"07",august:"08",septembrie:"09",octombrie:"10",noiembrie:"11",decembrie:"12"};const match=value.match(/(\d{1,2})\s+(\S+)\s+(\d{4})/);return match?`${match[3]}-${months[match[2]]||"01"}-${match[1].padStart(2,"0")}`:"";}
function rich(value:unknown){return normalizeRichText(value??"")}
function plain(value:unknown){return richTextToPlainText(value??"")}

function mapEvent(row:any):PublicEvent{return{id:row.slug,contentId:row.content_id,entityId:row.entity_id,title:row.title,date:date(row.starts_at),startDate:row.starts_at,endDate:row.ends_at||undefined,time:time(row.starts_at),place:row.venue||row.locality,venue:row.venue||undefined,locality:row.locality,category:row.category_name||"Eveniment",price:row.ticket_info||"Detalii la organizator",isFree:/gratuit|liber/i.test(row.ticket_info||""),image:media(row,row.image_url||"/images/campia-libertatii.jpg") as string,description:plain(row.description),descriptionRichText:rich(row.description),source:row.source_url||undefined,updatedAt:validDate(row.updated_at),verifiedAt:validDate(row.last_verified_at),address:row.address||undefined,organizer:row.organizer||undefined,accessibility:row.accessibility||undefined};}
function mapBusiness(row:any):PublicBusiness{return{id:row.slug,contentId:row.content_id,entityId:row.entity_id,name:row.name,category:row.category_name||"Servicii locale",locality:row.locality,phone:row.phone||undefined,email:row.contact_email||undefined,website:row.website||undefined,promoted:Boolean(row.promoted_tier),image:media(row,row.primary_image||undefined),description:plain(row.description),descriptionRichText:rich(row.description),source:row.source_url||undefined,verified:row.verification_status==="verified",verifiedAt:validDate(row.verified_at||row.last_verified_at),updatedAt:validDate(row.updated_at),address:row.address||undefined,latitude:row.latitude??undefined,longitude:row.longitude??undefined};}
function mapOffer(row:any):PublicOffer{return{id:row.slug,contentId:row.content_id,entityId:row.entity_id,title:row.title,business:row.business_name||"Afacere locală",category:row.category_name||undefined,locality:row.locality||undefined,price:money(row.price),priceValue:row.price??undefined,old:row.old_price==null?"":money(row.old_price),oldPriceValue:row.old_price??undefined,startsAt:row.starts_at,endsAt:row.ends_at,until:date(row.ends_at),image:media(row,row.image_url||undefined),description:plain(row.description),descriptionRichText:rich(row.description),terms:plain(row.terms)||undefined,termsRichText:rich(row.terms),availability:row.availability||undefined,source:row.source_url||undefined,promoted:Boolean(row.promoted_tier),updatedAt:validDate(row.updated_at),address:row.address||undefined,latitude:row.latitude??undefined,longitude:row.longitude??undefined};}
function mapRestaurant(row:any):PublicRestaurant{const description=plain(row.description);return{id:row.slug,contentId:row.content_id,entityId:row.entity_id,name:row.name,type:row.cuisine||"Restaurant",dish:[row.soup,row.main_dish].filter(Boolean).join(" · ")||description||"Meniul nu este publicat pentru astăzi",price:row.menu_price==null?"Preț necomunicat":money(row.menu_price),services:[row.delivery?"Livrare":"",row.pickup?"Ridicare":""].filter(Boolean).join(" · ")||"La locație",delivery:Boolean(row.delivery),pickup:Boolean(row.pickup),dietaryOptions:row.dietary_options||undefined,locality:row.locality||"Blaj",phone:row.phone||undefined,image:media(row,row.image_url||undefined),description,descriptionRichText:rich(row.description),source:row.source_url||undefined,updatedAt:validDate(row.menu_updated||row.updated_at),verifiedAt:validDate(row.last_verified_at),address:row.address||undefined,latitude:row.latitude??undefined,longitude:row.longitude??undefined};}
function mapJob(row:any):PublicJob{const salary=row.salary_min==null&&row.salary_max==null?"Salariu necomunicat":row.salary_min!=null&&row.salary_max!=null?`${money(row.salary_min)}–${money(row.salary_max)}`:money(row.salary_min??row.salary_max);return{id:row.slug,contentId:row.content_id,entityId:row.entity_id,title:row.title,company:row.company,locality:row.locality,type:row.contract_type||"Nespecificat",schedule:row.schedule||"Program de confirmat",salary,salaryDisclosed:row.salary_min!=null||row.salary_max!=null,transport:Boolean(row.transport_provided),description:plain(row.responsibilities),descriptionRichText:rich(row.responsibilities),requirements:plain(row.requirements)||undefined,requirementsRichText:rich(row.requirements),benefits:plain(row.benefits)||undefined,benefitsRichText:rich(row.benefits),applicationMethod:row.application_method||undefined,applyUrl:row.apply_url||undefined,deadline:validDate(row.deadline),source:row.source_url||undefined,updatedAt:validDate(row.updated_at),verifiedAt:validDate(row.last_verified_at),address:row.address||undefined,latitude:row.latitude??undefined,longitude:row.longitude??undefined};}
function mapPlace(row:any):PublicPlace{const description=plain(row.description);return{id:row.slug,contentId:row.content_id,entityId:row.entity_id,title:row.title,eyebrow:"Loc și poveste",image:media(row,row.image_url||"/images/palatul-cultural.jpg") as string,text:description,description,descriptionRichText:rich(row.description),source:row.source_url||"",locality:row.locality||"Blaj",updatedAt:validDate(row.updated_at),verifiedAt:validDate(row.last_verified_at),address:row.address||undefined,accessibility:row.accessibility||undefined};}
function mapPost(row:any):PublicPost{const author=typeof row.author_name==="string"&&!row.author_name.includes("@")?row.author_name:"Membru al comunității";return{id:row.slug,contentId:row.content_id,entityId:row.entity_id,title:row.title,excerpt:plain(row.excerpt),excerptRichText:rich(row.excerpt),body:plain(row.body),bodyRichText:rich(row.body),type:row.post_type,category:row.category_name||undefined,author,business:row.business_name||undefined,locality:row.locality||"Blaj",image:media(row),source:row.source_information||undefined,updatedAt:validDate(row.updated_at)};}
