/* eslint-disable @typescript-eslint/no-explicit-any -- public catalog adapters map heterogeneous D1 joins */
import { businesses as fallbackBusinesses, events as fallbackEvents, jobs as fallbackJobs, offers as fallbackOffers, places as fallbackPlaces, restaurants as fallbackRestaurants } from "../data";
import type { PublicBusiness, PublicCatalog, PublicEvent, PublicJob, PublicOffer, PublicPlace, PublicPost, PublicRestaurant } from "../public-types";
import { getRuntimeDb } from "../../db/runtime";

export async function loadPublicCatalog(): Promise<PublicCatalog> {
  try {
    const db=getRuntimeDb();
    const [eventRows,businessRows,offerRows,restaurantRows,jobRows,placeRows,postRows]=await Promise.all([
      db.prepare("SELECT c.id content_id,c.entity_id,c.is_demo,c.updated_at,(SELECT id FROM media_assets WHERE content_id=c.id AND approval_status='approved' AND media_status='active' ORDER BY created_at DESC LIMIT 1) cover_media_id,e.*,cat.name category_name FROM content_records c JOIN events e ON e.id=c.entity_id LEFT JOIN categories cat ON cat.id=e.category_id WHERE c.type='event' AND (c.status='published' OR (c.status='scheduled' AND datetime(c.scheduled_at)<=CURRENT_TIMESTAMP)) AND c.visibility='public' AND c.deleted_at IS NULL ORDER BY e.starts_at").all<any>(),
      db.prepare("SELECT c.id content_id,c.entity_id,c.is_demo,c.promoted_tier,c.updated_at,(SELECT id FROM media_assets WHERE content_id=c.id AND approval_status='approved' AND media_status='active' ORDER BY created_at DESC LIMIT 1) cover_media_id,b.*,cat.name category_name FROM content_records c JOIN businesses b ON b.id=c.entity_id LEFT JOIN categories cat ON cat.id=b.category_id WHERE c.type='business' AND (c.status='published' OR (c.status='scheduled' AND datetime(c.scheduled_at)<=CURRENT_TIMESTAMP)) AND c.visibility='public' AND c.deleted_at IS NULL AND b.deleted_at IS NULL ORDER BY c.featured DESC,b.name").all<any>(),
      db.prepare("SELECT c.id content_id,c.entity_id,c.is_demo,c.promoted_tier,c.updated_at,(SELECT id FROM media_assets WHERE content_id=c.id AND approval_status='approved' AND media_status='active' ORDER BY created_at DESC LIMIT 1) cover_media_id,o.*,b.name business_name FROM content_records c JOIN offers o ON o.id=c.entity_id LEFT JOIN businesses b ON b.id=o.business_id WHERE c.type='offer' AND (c.status='published' OR (c.status='scheduled' AND datetime(c.scheduled_at)<=CURRENT_TIMESTAMP)) AND c.visibility='public' AND c.deleted_at IS NULL ORDER BY o.ends_at").all<any>(),
      db.prepare("SELECT c.id content_id,c.entity_id,c.is_demo,c.updated_at,(SELECT id FROM media_assets WHERE content_id=c.id AND approval_status='approved' AND media_status='active' ORDER BY created_at DESC LIMIT 1) cover_media_id,r.*,dm.soup,dm.main_dish,dm.price menu_price,dm.updated_at menu_updated FROM content_records c JOIN restaurants r ON r.id=c.entity_id LEFT JOIN daily_menus dm ON dm.restaurant_id=r.id AND dm.status='published' AND dm.availability='active' WHERE c.type='restaurant' AND (c.status='published' OR (c.status='scheduled' AND datetime(c.scheduled_at)<=CURRENT_TIMESTAMP)) AND c.visibility='public' AND c.deleted_at IS NULL GROUP BY c.id ORDER BY r.name").all<any>(),
      db.prepare("SELECT c.id content_id,c.entity_id,c.is_demo,c.updated_at,(SELECT id FROM media_assets WHERE content_id=c.id AND approval_status='approved' AND media_status='active' ORDER BY created_at DESC LIMIT 1) cover_media_id,j.* FROM content_records c JOIN jobs j ON j.id=c.entity_id WHERE c.type='job' AND (c.status='published' OR (c.status='scheduled' AND datetime(c.scheduled_at)<=CURRENT_TIMESTAMP)) AND c.visibility='public' AND c.deleted_at IS NULL ORDER BY j.deadline").all<any>(),
      db.prepare("SELECT c.id content_id,c.entity_id,c.is_demo,c.updated_at,(SELECT id FROM media_assets WHERE content_id=c.id AND approval_status='approved' AND media_status='active' ORDER BY created_at DESC LIMIT 1) cover_media_id,p.* FROM content_records c JOIN places p ON p.id=c.entity_id WHERE c.type='place' AND (c.status='published' OR (c.status='scheduled' AND datetime(c.scheduled_at)<=CURRENT_TIMESTAMP)) AND c.visibility='public' AND c.deleted_at IS NULL ORDER BY c.featured DESC,p.id").all<any>(),
      db.prepare("SELECT c.id content_id,c.entity_id,c.is_demo,c.updated_at,(SELECT id FROM media_assets WHERE content_id=c.id AND approval_status='approved' AND media_status='active' ORDER BY created_at DESC LIMIT 1) cover_media_id,c.title,c.excerpt,c.slug,p.post_type,p.body,p.locality,p.source_information,u.display_name author_name,b.name business_name FROM content_records c JOIN posts p ON p.id=c.entity_id LEFT JOIN users u ON u.id=p.author_user_id LEFT JOIN businesses b ON b.id=p.business_id WHERE c.type IN ('community_post','local_story','article','business_update') AND (c.status='published' OR (c.status='scheduled' AND datetime(c.scheduled_at)<=CURRENT_TIMESTAMP)) AND c.visibility='public' AND c.deleted_at IS NULL ORDER BY c.published_at DESC").all<any>(),
    ]);
    const catalog:PublicCatalog={
      events:eventRows.results.map(row=>mapEvent(row)),businesses:businessRows.results.map(row=>mapBusiness(row)),offers:offerRows.results.map(row=>mapOffer(row)),restaurants:restaurantRows.results.map(row=>mapRestaurant(row)),jobs:jobRows.results.map(row=>mapJob(row)),places:placeRows.results.map(row=>mapPlace(row)),posts:postRows.results.map(row=>mapPost(row)),
    };
    if(Object.values(catalog).some(items=>items.length))return catalog;
  }catch(error){console.error("public_catalog_fallback",error instanceof Error?error.message:"unknown")}
  return {events:fallbackEvents.map(item=>({...item,isDemo:true})),businesses:fallbackBusinesses.map(item=>({...item,isDemo:true})),offers:fallbackOffers.map(item=>({...item,isDemo:true})),restaurants:fallbackRestaurants.map(item=>({...item,isDemo:true})),jobs:fallbackJobs.map(item=>({...item,isDemo:true})),places:fallbackPlaces.map(item=>({...item,isDemo:true})),posts:[]};
}

function date(value:string){try{return new Intl.DateTimeFormat("ro-RO",{day:"numeric",month:"long",year:"numeric",timeZone:"Europe/Bucharest"}).format(new Date(value))}catch{return value}}
function time(value:string){try{return new Intl.DateTimeFormat("ro-RO",{hour:"2-digit",minute:"2-digit",timeZone:"Europe/Bucharest"}).format(new Date(value))}catch{return ""}}
function money(value:number|null|undefined){return value==null?"Preț necomunicat":`${new Intl.NumberFormat("ro-RO").format(value)} lei`}
function media(row:any,fallback?:string){return row.cover_media_id?`/api/media/${row.cover_media_id}`:fallback}
function mapEvent(row:any):PublicEvent{return{id:row.slug,contentId:row.content_id,entityId:row.entity_id,title:row.title,date:date(row.starts_at),startDate:row.starts_at,time:time(row.starts_at),place:row.venue||row.locality,locality:row.locality,category:row.category_name||"Eveniment",price:row.ticket_info||"Detalii la organizator",image:media(row,row.image_url||"/images/campia-libertatii.jpg") as string,description:row.description||"",source:row.source_url||undefined,isDemo:Boolean(row.is_demo),updatedAt:row.updated_at}}
function mapBusiness(row:any):PublicBusiness{return{id:row.slug,contentId:row.content_id,entityId:row.entity_id,name:row.name,category:row.category_name||"Servicii locale",locality:row.locality,phone:row.phone||"Telefon necomunicat",promoted:Boolean(row.promoted_tier),image:media(row,row.primary_image||undefined),description:row.description||"",source:row.source_url||undefined,isDemo:Boolean(row.is_demo),verified:row.verification_status==="verified",updatedAt:row.updated_at}}
function mapOffer(row:any):PublicOffer{return{id:row.slug,contentId:row.content_id,entityId:row.entity_id,title:row.title,business:row.business_name||"Afacere locală",price:money(row.price),old:row.old_price==null?"":money(row.old_price),until:date(row.ends_at),image:media(row,row.image_url||undefined),description:row.description||row.terms||"",source:row.source_url||undefined,isDemo:Boolean(row.is_demo),promoted:Boolean(row.promoted_tier),updatedAt:row.updated_at}}
function mapRestaurant(row:any):PublicRestaurant{return{id:row.slug,contentId:row.content_id,entityId:row.entity_id,name:row.name,type:row.cuisine||"Restaurant",dish:[row.soup,row.main_dish].filter(Boolean).join(" · ")||row.description||"Meniu în curs de actualizare",price:row.menu_price==null?"Preț necomunicat":money(row.menu_price),services:[row.delivery?"Livrare":"",row.pickup?"Ridicare":""].filter(Boolean).join(" · ")||"La locație",image:media(row,row.image_url||undefined),description:row.description||"",source:row.source_url||undefined,isDemo:Boolean(row.is_demo),updatedAt:row.menu_updated||row.updated_at}}
function mapJob(row:any):PublicJob{const salary=row.salary_min==null&&row.salary_max==null?"Salariu comunicat la interviu":row.salary_min!=null&&row.salary_max!=null?`${money(row.salary_min)}–${money(row.salary_max)}`:money(row.salary_min||row.salary_max);return{id:row.slug,contentId:row.content_id,entityId:row.entity_id,title:row.title,company:row.company,locality:row.locality,type:row.contract_type||"Nespecificat",schedule:row.schedule||"Program de confirmat",salary,transport:Boolean(row.transport_provided),description:row.responsibilities||"",source:row.source_url||undefined,isDemo:Boolean(row.is_demo),updatedAt:row.updated_at}}
function mapPlace(row:any):PublicPlace{return{id:row.slug,contentId:row.content_id,entityId:row.entity_id,title:row.title,eyebrow:"Loc și poveste",image:media(row,row.image_url||"/images/palatul-cultural.jpg") as string,text:row.description||"",source:row.source_url||"",locality:row.locality||"Blaj",isDemo:Boolean(row.is_demo),updatedAt:row.updated_at}}
function mapPost(row:any):PublicPost{const author=typeof row.author_name==="string"&&!row.author_name.includes("@")?row.author_name:"Membru al comunității";return{id:row.slug,contentId:row.content_id,entityId:row.entity_id,title:row.title,excerpt:row.excerpt||"",body:row.body||"",type:row.post_type,author,business:row.business_name||undefined,locality:row.locality||"Blaj",image:media(row),source:row.source_information||undefined,isDemo:Boolean(row.is_demo),updatedAt:row.updated_at}}
