"use client";

/* eslint-disable @next/next/no-img-element -- Admin previews use runtime D1/R2 media URLs. */

import { Grid3X3, List, Search, Upload } from "lucide-react";
import { useMemo, useState } from "react";
import { MediaAdminActions, MediaCleanupAction } from "../ui/AdminActions";

type MediaRow = { id:number; title:string|null; original_filename:string|null; alt_text:string|null; photographer:string|null; source_url:string|null; license:string|null; approval_status:string; media_status:string; mime_type:string|null; owner_name:string|null; business_name:string|null; created_at:string; usage_count:number };

export function AdminMediaLibrary({ items }: { items: MediaRow[] }) {
  const [query,setQuery]=useState(""); const [approval,setApproval]=useState("all"); const [type,setType]=useState("all"); const [owner,setOwner]=useState("all"); const [usage,setUsage]=useState("all"); const [date,setDate]=useState("all"); const [now]=useState(Date.now); const [layout,setLayout]=useState<"grid"|"list">("grid"); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  const visible=useMemo(()=>items.filter(item=>{const ageDays=(now-new Date(item.created_at).getTime())/86_400_000;return (approval==="all"||item.approval_status===approval)&&(type==="all"||item.mime_type===type)&&(owner==="all"||(owner==="owned"?Boolean(item.owner_name):!item.owner_name))&&(usage==="all"||(usage==="used"?item.usage_count>0:item.usage_count===0))&&(date==="all"||(date==="7"?ageDays<=7:date==="30"?ageDays<=30:ageDays>30))&&`${item.title} ${item.original_filename} ${item.alt_text} ${item.photographer} ${item.owner_name}`.toLowerCase().includes(query.toLowerCase());}),[items,approval,type,owner,usage,date,query,now]);
  async function upload(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const response=await fetch("/api/media",{method:"POST",body:new FormData(event.currentTarget)});const data=await response.json() as{error?:string};if(response.ok)location.reload();else setMessage(data.error||"Imaginea nu a putut fi încărcată.");setBusy(false)}
  return <>
    <section className="admin-media-tools">
      <form className="admin-media-upload" onSubmit={upload}>
        <h2><Upload/>Încarcă imagine</h2><div className="editor-grid"><label>Fișier JPG, PNG sau WebP<input name="file" type="file" accept="image/jpeg,image/png,image/webp" required/></label><label>Titlu<input name="title" maxLength={240}/></label><label>Text alternativ<input name="altText" maxLength={500} required/></label><label>Autor / fotograf<input name="photographer" maxLength={240}/></label><label>Sursă HTTP/HTTPS<input name="sourceUrl" type="url" maxLength={800}/></label><label>Licență / permisiune<input name="license" maxLength={120}/></label></div><button className="button" disabled={busy}>{busy?"Se încarcă…":"Încarcă în bibliotecă"}</button>{message&&<p role="alert" className="error-message">{message}</p>}
      </form>
      <div className="media-toolbar"><label><Search/>Caută<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Titlu, fișier, autor…"/></label><label>Aprobare<select value={approval} onChange={event=>setApproval(event.target.value)}><option value="all">Toate</option><option value="pending">În așteptare</option><option value="approved">Aprobate</option><option value="rejected">Respinse</option></select></label><label>Tip<select value={type} onChange={event=>setType(event.target.value)}><option value="all">Toate</option><option value="image/jpeg">JPG</option><option value="image/png">PNG</option><option value="image/webp">WebP</option></select></label><label>Proprietar<select value={owner} onChange={event=>setOwner(event.target.value)}><option value="all">Toți</option><option value="owned">Cu proprietar</option><option value="anonymous">Fără proprietar</option></select></label><label>Utilizare<select value={usage} onChange={event=>setUsage(event.target.value)}><option value="all">Orice utilizare</option><option value="used">Folosite</option><option value="orphan">Nefolosite</option></select></label><label>Dată<select value={date} onChange={event=>setDate(event.target.value)}><option value="all">Oricând</option><option value="7">Ultimele 7 zile</option><option value="30">Ultimele 30 zile</option><option value="older">Mai vechi</option></select></label><div className="layout-toggle" aria-label="Afișare"><button aria-pressed={layout==="grid"} onClick={()=>setLayout("grid")}><Grid3X3/>Grilă</button><button aria-pressed={layout==="list"} onClick={()=>setLayout("list")}><List/>Listă</button></div><MediaCleanupAction/></div>
    </section>
    <p aria-live="polite">{visible.length} imagini</p>
    <div className={`admin-media-library ${layout}`}>{visible.map(item=><article className="admin-media-card" key={item.id}><img src={`/api/media/${item.id}`} alt={item.alt_text||""} width="640" height="420" loading="lazy"/><div><span className={`status-pill status-${item.approval_status}`}>{item.approval_status}</span><h3>{item.title||item.original_filename||`Media #${item.id}`}</h3><p>{item.owner_name||"Contribuție anonimă"}{item.business_name?` · ${item.business_name}`:""}</p><small>{item.mime_type||"tip necunoscut"} · {item.usage_count} referințe · {item.created_at}</small><MediaAdminActions id={item.id} status={item.approval_status} altText={item.alt_text||""} title={item.title||""} photographer={item.photographer||""} sourceUrl={item.source_url||""} license={item.license||""}/></div></article>)}</div>
  </>;
}
