/* eslint-disable @typescript-eslint/no-explicit-any -- raw D1 administration rows vary by section */
import Link from "next/link";
import { Archive, BriefcaseBusiness, FileText, History, Inbox, LogOut, Menu, Settings, ShieldCheck, Store, Tag, UserRound } from "lucide-react";
import { getRuntimeDb } from "../../db/runtime";
import { getContentForEditor } from "../server/content";
import { chatGPTSignOutPath } from "../chatgpt-auth";
import { isAdmin, PlatformError, requireAccountForPage } from "../server/platform";
import { BusinessAdminActions, ClaimActions, ModerationActions, PermanentDelete, UserActions } from "../ui/AdminActions";
import { ContentEditor, statusLabels, typeLabels } from "../ui/Management";

const nav=[[/^$/, "/admin","Rezumat",Store],[/^moderare/,"/admin/moderare","Moderare",Inbox],[/^continut/,"/admin/continut","Conținut",FileText],[/^afaceri|^revendicari/,"/admin/afaceri","Afaceri",BriefcaseBusiness],[/^utilizatori/,"/admin/utilizatori","Utilizatori",UserRound],[/^categorii/,"/admin/categorii","Categorii",Tag],[/^media/,"/admin/media","Media",Archive],[/^raportari/,"/admin/raportari","Raportări",ShieldCheck],[/^audit/,"/admin/audit","Audit",History],[/^setari/,"/admin/setari","Setări",Settings]] as const;

export async function AdminExperience({path}:{path:string[]}){
  const returnTo=`/admin${path.length?`/${path.join("/")}`:""}`;const account=await requireAccountForPage(returnTo);if(!isAdmin(account))throw new PlatformError(403,"Administrarea este disponibilă doar conturilor autorizate.");const db=getRuntimeDb();const section=path[0]||"";let content:React.ReactNode;
  if(!section){const [moderation,changes,claims,published,reports,users,audit]=await Promise.all([
    count("SELECT COUNT(*) count FROM content_records WHERE moderation_state='pending_review' AND deleted_at IS NULL"),count("SELECT COUNT(*) count FROM content_records WHERE moderation_state='needs_changes' AND deleted_at IS NULL"),count("SELECT COUNT(*) count FROM business_claims WHERE status IN ('pending_review','needs_changes')"),count("SELECT COUNT(*) count FROM content_records WHERE status='published' AND deleted_at IS NULL"),count("SELECT COUNT(*) count FROM content_reports WHERE status='new'"),count("SELECT COUNT(*) count FROM users WHERE created_at>=datetime('now','-30 days')"),db.prepare("SELECT a.*,u.display_name actor_name FROM audit_logs a LEFT JOIN users u ON u.id=a.actor_user_id ORDER BY a.created_at DESC LIMIT 8").all()]);const cards=[["Moderare în așteptare",moderation,Inbox],["Necesită modificări",changes,FileText],["Revendicări active",claims,BriefcaseBusiness],["Conținut publicat",published,Store],["Raportări noi",reports,ShieldCheck],["Conturi noi (30 zile)",users,UserRound]] as const;content=<><AdminTitle title={`Bun venit, ${account.displayName}`} copy="Indicatori reali și activitatea recentă a platformei."/><div className="admin-cards">{cards.map(([title,value,Icon])=><article key={title}><Icon/><strong>{value}</strong><span>{title}</span></article>)}</div><section className="admin-panel"><h2>Activitate recentă</h2><div className="audit-list">{audit.results.map((row:any)=><div key={row.id}><strong>{row.actor_name||"Sistem"}</strong><span>{row.action}</span><small>{row.entity_type} #{row.entity_id||"—"} · {row.created_at}</small></div>)}</div></section></>}
  else if(section==="moderare"){const queue=await db.prepare("SELECT c.*,u.display_name author_name,b.name business_name FROM content_records c LEFT JOIN users u ON u.id=c.owner_user_id LEFT JOIN businesses b ON b.id=c.business_id WHERE c.moderation_state='pending_review' AND c.deleted_at IS NULL ORDER BY c.submitted_at LIMIT 200").all<any>();content=<><AdminTitle title="Moderare" copy="Materialele rămân private până la o decizie explicită."/><div className="admin-stack">{queue.results.map(item=><article className="admin-review" key={item.id}><header><span className="status-pill status-pending_review">În verificare</span><small>{typeLabels[item.type]||item.type} · {item.submitted_at}</small><h2>{item.title}</h2><p>{item.excerpt}</p></header><dl><div><dt>Autor</dt><dd>{item.author_name||"Necunoscut"}</dd></div><div><dt>Afacere</dt><dd>{item.business_name||"—"}</dd></div><div><dt>Versiune</dt><dd>{item.version}</dd></div></dl><ModerationActions id={item.id}/></article>)}</div>{!queue.results.length&&<Empty title="Coada de moderare este goală."/>}</>}
  else if(section==="revendicari"){const claims=await db.prepare("SELECT bc.*,b.name business_name,u.display_name requester_name,u.email requester_email FROM business_claims bc JOIN businesses b ON b.id=bc.business_id JOIN users u ON u.id=bc.requester_user_id WHERE bc.status IN ('pending_review','needs_changes') ORDER BY bc.submitted_at").all<any>();content=<><AdminTitle title="Revendicări" copy="Dovezile sunt informații private și nu apar pe profilul public."/><div className="admin-stack">{claims.results.map(claim=><article className="admin-review" key={claim.id}><h2>{claim.business_name}</h2><p>{claim.requester_name} · {claim.requester_email}</p><p>{claim.explanation}</p>{claim.evidence_url&&<a href={claim.evidence_url} target="_blank" rel="noreferrer">Deschide dovada</a>}<ClaimActions id={claim.id}/></article>)}</div></>}
  else if(section==="afaceri"){const rows=await db.prepare("SELECT b.*,COUNT(bm.id) member_count FROM businesses b LEFT JOIN business_memberships bm ON bm.business_id=b.id AND bm.membership_status='active' WHERE b.deleted_at IS NULL GROUP BY b.id ORDER BY b.updated_at DESC LIMIT 200").all<any>();content=<><AdminTitle title="Afaceri" copy="Verificare, vizibilitate și membri autorizați." action={<Link className="button" href="/admin/revendicari">Vezi revendicările</Link>}/><div className="management-list">{rows.results.map(item=><article className="management-row" key={item.id}><div><span className={`status-pill status-${item.status}`}>{statusLabels[item.status]||item.status}</span><h3>{item.name}</h3><p>{item.locality} · {item.member_count} membri activi · {item.verification_status}</p></div><div><Link href={`/cont/afaceri/${item.id}`}>Deschide</Link><BusinessAdminActions id={item.id} verified={item.verification_status==="verified"} status={item.status}/></div></article>)}</div></>}
  else if(section==="continut"){
    if(path[1]==="nou"){const bs=await db.prepare("SELECT id,name FROM businesses WHERE deleted_at IS NULL ORDER BY name").all<any>();content=<><AdminTitle title="Conținut nou" copy="Administratorii pot crea orice tip, apoi îl pot publica prin fluxul de moderare."/><ContentEditor businesses={bs.results}/></>}
    else if(path[1]&&path[2]){const item=await getContentForEditor(account,Number(path[2]));const bs=await db.prepare("SELECT id,name FROM businesses WHERE deleted_at IS NULL ORDER BY name").all<any>();content=<><AdminTitle title="Editează conținut" copy="Modificările folosesc control optimist al versiunii."/><ContentEditor initial={item as never} businesses={bs.results}/>{item?.status==="soft_deleted"&&account.globalRole==="platform_owner"&&<PermanentDelete id={item.id} title={item.title}/>}</>}
    else{const rows=await db.prepare("SELECT c.*,u.display_name author_name,b.name business_name FROM content_records c LEFT JOIN users u ON u.id=c.owner_user_id LEFT JOIN businesses b ON b.id=c.business_id ORDER BY c.updated_at DESC LIMIT 200").all<any>();content=<><AdminTitle title="Conținut" copy="Căutare, filtrare și acțiuni reversibile asupra conținutului persistent." action={<Link className="button" href="/admin/continut/nou">Adaugă</Link>}/><div className="management-list">{rows.results.map(item=><article className="management-row" key={item.id}><div><span className={`status-pill status-${item.status}`}>{statusLabels[item.status]||item.status}</span><small>{typeLabels[item.type]||item.type}</small><h3>{item.title}</h3><p>{item.author_name||"Administrator"}{item.business_name?` · ${item.business_name}`:""}</p></div><Link href={`/admin/continut/${item.type}/${item.id}`}>Editează</Link></article>)}</div></>}
  }
  else if(section==="utilizatori"){const rows=await db.prepare("SELECT id,email,display_name,global_role,account_status,created_at,last_login_at FROM users ORDER BY created_at DESC LIMIT 200").all<any>();content=<><AdminTitle title="Utilizatori" copy="Rolurile administrative pot fi gestionate numai de proprietarul platformei."/><div className="admin-stack">{rows.results.map(user=><article className="admin-review" key={user.id}><h2>{user.display_name}</h2><p>{user.email} · {roleLabel(user.global_role)} · {user.account_status}</p><small>Ultima conectare: {user.last_login_at}</small><UserActions id={user.id} role={user.global_role} status={user.account_status} platformOwner={account.globalRole==="platform_owner"}/></article>)}</div></>}
  else if(section==="categorii"){const rows=await db.prepare("SELECT c.*,COUNT(cr.id) usage_count FROM categories c LEFT JOIN content_records cr ON cr.type=c.type GROUP BY c.id ORDER BY c.type,c.name").all<any>();content=<><AdminTitle title="Categorii" copy="Taxonomia folosită de editoare și listări."/><div className="management-list">{rows.results.map(row=><article className="management-row" key={row.id}><div><small>{row.type}</small><h3>{row.name}</h3><p>{row.usage_count} materiale asociate tipului</p></div></article>)}</div></>}
  else if(section==="media"){const rows=await db.prepare("SELECT m.*,u.display_name owner_name FROM media_assets m LEFT JOIN users u ON u.id=m.owner_user_id WHERE m.media_status!='soft_deleted' ORDER BY m.created_at DESC LIMIT 200").all<any>();content=<><AdminTitle title="Biblioteca media" copy="Fișiere private, atribuiri, proprietari și starea aprobării."/><div className="management-list">{rows.results.map(row=><article className="management-row" key={row.id}><div><span className="status-pill">{row.approval_status}</span><h3>{row.title||row.original_filename||`Media #${row.id}`}</h3><p>{row.owner_name||"Contribuție anonimă"} · {row.mime_type||"tip necunoscut"} · {row.alt_text||"Alt text lipsește"}</p></div></article>)}</div></>}
  else if(section==="raportari"){const rows=await db.prepare("SELECT * FROM content_reports ORDER BY created_at DESC LIMIT 200").all<any>();content=<><AdminTitle title="Raportări" copy="Sesizări despre informații incorecte sau conținut problematic."/><div className="management-list">{rows.results.map(row=><article className="management-row" key={row.id}><div><span className="status-pill">{row.status}</span><h3>{row.entity_type||"Raportare generală"} #{row.entity_id||"—"}</h3><p>{row.reason}</p><time>{row.created_at}</time></div></article>)}</div></>}
  else if(section==="audit"){const rows=await db.prepare("SELECT a.*,u.display_name actor_name FROM audit_logs a LEFT JOIN users u ON u.id=a.actor_user_id ORDER BY a.created_at DESC LIMIT 300").all<any>();content=<><AdminTitle title="Istoric audit" copy="Jurnal operațional doar în citire. Nu există acțiuni de ștergere."/><div className="audit-list">{rows.results.map(row=><div key={row.id}><strong>{row.actor_name||"Sistem"}</strong><span>{row.action}</span><small>{row.entity_type} #{row.entity_id||"—"} · {row.created_at}</small></div>)}</div></>}
  else if(section==="promovari"){const rows=await db.prepare("SELECT * FROM promoted_placements ORDER BY starts_at DESC LIMIT 200").all<any>();content=<><AdminTitle title="Promovări" copy="Etichetele promovate sunt administrate separat de proprietarii afacerilor."/><div className="management-list">{rows.results.map(row=><article className="management-row" key={row.id}><div><span className="status-pill">{row.status}</span><h3>{row.entity_type} #{row.entity_id}</h3><p>{row.tier} · {row.starts_at} — {row.ends_at}</p></div></article>)}</div></>}
  else if(section==="setari")content=<><AdminTitle title="Setări platformă" copy="Configurații protejate și retenție."/><section className="admin-panel"><h2>Roluri și bootstrap</h2><p>Adresa configurată în mediul securizat este folosită numai pentru primul proprietar al platformei. După persistență, rolurile se gestionează din baza de date.</p><h2>Retenție</h2><p>Ștergerea permanentă este limitată proprietarului platformei și verifică perioada de retenție. Auditul nu este șters.</p></section></>;
  else content=<Empty title="Secțiune indisponibilă."/>;
  return <section className="admin-shell"><aside><div className="logo"><span>Blaj</span><b>Azi</b></div><p>Administrare</p><nav>{nav.map(([pattern,href,label,Icon])=><Link className={pattern.test(section)?"active":""} href={href} key={href}><Icon/>{label}</Link>)}</nav><Link href={chatGPTSignOutPath("/")}><LogOut/>Deconectare</Link></aside><details className="admin-mobile-nav"><summary><Menu/> Meniu administrare</summary><nav>{nav.map(([,href,label])=><Link href={href} key={href}>{label}</Link>)}</nav></details><div className="admin-content">{content}</div></section>;
  async function count(sql:string){return (await db.prepare(sql).first<{count:number}>())?.count||0}
}
function AdminTitle({title,copy,action}:{title:string;copy:string;action?:React.ReactNode}){return <header className="admin-title"><div><p className="eyebrow">Administrare Blaj Azi</p><h1>{title}</h1><p>{copy}</p></div>{action}</header>}
function Empty({title}:{title:string}){return <div className="management-empty"><h2>{title}</h2></div>}
function roleLabel(role:string){return role==="business_owner"?"Proprietar de afacere":role==="admin"?"Administrator":role==="platform_owner"?"Proprietar platformă":"Utilizator"}
