/* eslint-disable @typescript-eslint/no-explicit-any -- raw D1 administration rows vary by section */
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { Archive, BriefcaseBusiness, Database, FileText, History, Inbox, LayoutTemplate, LogOut, Menu, Settings, ShieldCheck, Store, Tag, UserRound } from "lucide-react";
import { getRuntimeDb } from "../../db/runtime";
import { getContentForEditor } from "../server/content";
import { isAdmin, requireAccountForPage } from "../server/platform";
import { listAdminSiteContent, listSiteContentRevisions, loadAdminSiteContent } from "../server/site-content";
import { AdminContentActions, BusinessAdminActions, CategoryActions, CategoryCreate, ClaimActions, ModerationActions, PermanentDelete, PromotionActions, PromotionCreate, ReportActions, UserActions } from "../ui/AdminActions";
import { ContentAction, ContentEditor, ContentList, statusLabels, typeLabels } from "../ui/Management";
import { SiteContentEditor, SiteContentIndex } from "./SiteContentAdmin";
import { AdminMediaLibrary } from "./AdminMediaLibrary";
import { DemoDataAdmin } from "./DemoDataAdmin";
import { demoDataCapabilityEnabled, getDemoDataStatus } from "../server/demo-data";

const baseNav=[[/^$/, "/admin","Rezumat",Store],[/^pagini/,"/admin/pagini","Pagini și texte",LayoutTemplate],[/^moderare/,"/admin/moderare","Moderare",Inbox],[/^expirari/,"/admin/expirari","Expirări",Archive],[/^continut/,"/admin/continut","Conținut",FileText],[/^afaceri|^revendicari/,"/admin/afaceri","Afaceri",BriefcaseBusiness],[/^utilizatori/,"/admin/utilizatori","Utilizatori",UserRound],[/^categorii/,"/admin/categorii","Categorii",Tag],[/^media/,"/admin/media","Media",Archive],[/^raportari/,"/admin/raportari","Raportări",ShieldCheck],[/^promovari/,"/admin/promovari","Promovări",Tag],[/^audit/,"/admin/audit","Audit",History],[/^setari/,"/admin/setari","Setări",Settings]] as const;

export async function AdminExperience({path}:{path:string[]}){
  const returnTo=`/admin${path.length?`/${path.join("/")}`:""}`;const account=await requireAccountForPage(returnTo,"/admin/conectare");if(!isAdmin(account))redirect("/cont?acces=administrare");const db=getRuntimeDb();const section=path[0]||"";const demoEnabled=demoDataCapabilityEnabled();const nav=demoEnabled?[...baseNav.slice(0,-1),[/^date-demonstrative/,"/admin/date-demonstrative","Date demonstrative",Database] as const,baseNav.at(-1)!]:baseNav;let content:React.ReactNode;
  if(!section){const [moderation,changes,claims,awaiting,published,expiring,reports,users,audit]=await Promise.all([
    count("SELECT COUNT(*) count FROM content_records WHERE moderation_state='pending_review' AND deleted_at IS NULL"),count("SELECT COUNT(*) count FROM content_records WHERE moderation_state='needs_changes' AND deleted_at IS NULL"),count("SELECT COUNT(*) count FROM business_claims WHERE status IN ('pending_review','needs_changes')"),count("SELECT COUNT(*) count FROM businesses WHERE moderation_status='pending_review' OR verification_status='pending_review'"),count("SELECT COUNT(*) count FROM content_records WHERE status='published' AND deleted_at IS NULL"),count("SELECT (SELECT COUNT(*) FROM events WHERE status='published' AND starts_at BETWEEN datetime('now') AND datetime('now','30 days'))+(SELECT COUNT(*) FROM offers WHERE status='published' AND ends_at BETWEEN date('now') AND date('now','30 days'))+(SELECT COUNT(*) FROM jobs WHERE status='published' AND deadline BETWEEN date('now') AND date('now','30 days')) count"),count("SELECT COUNT(*) count FROM content_reports WHERE status='new'"),count("SELECT COUNT(*) count FROM users WHERE created_at>=datetime('now','-30 days')"),db.prepare("SELECT a.*,u.display_name actor_name FROM audit_logs a LEFT JOIN users u ON u.id=a.actor_user_id ORDER BY a.created_at DESC LIMIT 8").all()]);const cards=[["Moderare în așteptare",moderation,Inbox],["Necesită modificări",changes,FileText],["Revendicări active",claims,BriefcaseBusiness],["Afaceri de verificat",awaiting,BriefcaseBusiness],["Conținut publicat",published,Store],["Expiră în 30 zile",expiring,Archive],["Raportări noi",reports,ShieldCheck],["Conturi noi (30 zile)",users,UserRound]] as const;content=<><AdminTitle title={`Bun venit, ${account.displayName}`} copy="Indicatori reali și activitatea recentă a platformei."/><div className="admin-cards">{cards.map(([title,value,Icon])=><article key={title}><Icon/><strong>{value}</strong><span>{title}</span></article>)}</div><section className="admin-panel"><h2>Activitate recentă</h2><div className="audit-list">{audit.results.map((row:any)=><div key={row.id}><strong>{row.actor_name||"Sistem"}</strong><span>{row.action}</span><small>{row.entity_type} #{row.entity_id||"—"} · {row.created_at}</small></div>)}</div></section></>}
  else if(section==="pagini"){
    if(path[1]){const key=decodeURIComponent(path[1]);const [entry,revisions]=await Promise.all([loadAdminSiteContent(account,key),listSiteContentRevisions(account,key)]);content=<><AdminTitle title={entry.label} copy="Editează o ciornă validată, previzualizează componentele publice și publică numai când modificările sunt pregătite." action={<Link className="button button-outline" href="/admin/pagini">Toate paginile</Link>}/><SiteContentEditor initial={entry} revisions={revisions.results}/></>}
    else{const entries=await listAdminSiteContent(account);content=<><AdminTitle title="Pagini și texte" copy="Conținut editorial, navigație, formulare, stări goale și metadate SEO administrate fără modificarea codului."/><SiteContentIndex entries={entries}/></>}
  }
  else if(section==="moderare"){const queue=await db.prepare("SELECT c.*,u.display_name author_name,b.name business_name,CASE WHEN c.status='published' THEN CAST(json_extract((SELECT snapshot FROM content_revisions WHERE entity_type='content' AND entity_id=c.id AND moderation_status='pending_review' ORDER BY revision_number DESC LIMIT 1),'$.primaryMediaId') AS INTEGER) WHEN c.primary_media_state='selected' THEN c.primary_media_id WHEN c.primary_media_state='none' THEN NULL ELSE (SELECT id FROM media_assets WHERE content_id=c.id AND media_status='active' ORDER BY created_at DESC,id DESC LIMIT 1) END review_media_id,CASE WHEN c.status='published' THEN json_extract((SELECT snapshot FROM content_revisions WHERE entity_type='content' AND entity_id=c.id AND moderation_status='pending_review' ORDER BY revision_number DESC LIMIT 1),'$.primaryMediaAltText') WHEN c.primary_media_state='selected' THEN c.primary_media_alt_text ELSE (SELECT alt_text FROM media_assets WHERE content_id=c.id AND media_status='active' ORDER BY created_at DESC,id DESC LIMIT 1) END review_media_alt FROM content_records c LEFT JOIN users u ON u.id=c.owner_user_id LEFT JOIN businesses b ON b.id=c.business_id WHERE c.moderation_state='pending_review' AND c.deleted_at IS NULL ORDER BY c.submitted_at LIMIT 200").all<any>();content=<><AdminTitle title="Moderare" copy="Materialele rămân private până la o decizie explicită."/><div className="admin-stack">{queue.results.map(item=><article className="admin-review" key={item.id}><header><span className="status-pill status-pending_review">În verificare</span><small>{typeLabels[item.type]||item.type} · {item.submitted_at}</small><h2>{item.title}</h2><p>{item.excerpt}</p>{item.review_media_id&&<img className="moderation-media-preview" src={`/api/media/${item.review_media_id}?width=768`} alt={item.review_media_alt||item.title} width="768" height="512"/>}</header><dl><div><dt>Autor</dt><dd>{item.author_name||"Necunoscut"}</dd></div><div><dt>Afacere</dt><dd>{item.business_name||"—"}</dd></div><div><dt>Versiune</dt><dd>{item.version}</dd></div></dl><ModerationActions id={item.id}/></article>)}</div>{!queue.results.length&&<Empty title="Coada de moderare este goală."/>}</>}
  else if(section==="expirari"){
    const rows=await db.prepare("SELECT queue.*,(datetime(queue.due_at)<datetime('now')) is_expired FROM (SELECT c.id,c.type,c.title,c.status,CASE WHEN c.type='event' THEN (SELECT COALESCE(ends_at,starts_at) FROM events WHERE id=c.entity_id) WHEN c.type='offer' THEN (SELECT ends_at FROM offers WHERE id=c.entity_id) WHEN c.type='job' THEN (SELECT deadline FROM jobs WHERE id=c.entity_id) ELSE c.expires_at END due_at FROM content_records c WHERE c.status='published' AND c.deleted_at IS NULL AND c.type IN ('event','offer','job')) queue WHERE queue.due_at IS NOT NULL AND datetime(queue.due_at)<=datetime('now','+30 days') ORDER BY datetime(queue.due_at)").all<any>();
    content=<><AdminTitle title="Expirări și reverificare" copy="Evenimente, oferte și joburi expirate sau care ajung la termen în următoarele 30 de zile."/><div className="management-list">{rows.results.map(item=><article className="management-row" key={item.id}><div><span className={`status-pill ${item.is_expired?"status-rejected":"status-pending_review"}`}>{item.is_expired?"Expirat":"Expiră curând"}</span><small>{typeLabels[item.type]||item.type}</small><h3>{item.title}</h3><p>Termen: {item.due_at}</p></div><Link href={`/admin/continut/${item.type}/${item.id}`}>Revizuiește</Link></article>)}</div>{!rows.results.length&&<Empty title="Nu există materiale care expiră în următoarele 30 de zile."/>}</>;
  }
  else if(section==="revendicari"){const claims=await db.prepare("SELECT bc.*,b.name business_name,u.display_name requester_name,u.email requester_email FROM business_claims bc JOIN businesses b ON b.id=bc.business_id JOIN users u ON u.id=bc.requester_user_id WHERE bc.status IN ('pending_review','needs_changes') ORDER BY bc.submitted_at").all<any>();content=<><AdminTitle title="Revendicări" copy="Dovezile sunt informații private și nu apar pe profilul public."/><div className="admin-stack">{claims.results.map(claim=><article className="admin-review" key={claim.id}><h2>{claim.business_name}</h2><p>{claim.requester_name} · {claim.requester_email}</p><p>{claim.explanation}</p>{claim.evidence_url&&<a href={claim.evidence_url} target="_blank" rel="noreferrer">Deschide dovada</a>}<ClaimActions id={claim.id}/></article>)}</div></>}
  else if(section==="afaceri"){const rows=await db.prepare("SELECT b.*,COUNT(bm.id) member_count FROM businesses b LEFT JOIN business_memberships bm ON bm.business_id=b.id AND bm.membership_status='active' WHERE b.deleted_at IS NULL GROUP BY b.id ORDER BY b.updated_at DESC LIMIT 200").all<any>();content=<><AdminTitle title="Afaceri" copy="Verificare, vizibilitate și membri autorizați." action={<Link className="button" href="/admin/revendicari">Vezi revendicările</Link>}/><div className="management-list">{rows.results.map(item=><article className="management-row" key={item.id}><div><span className={`status-pill status-${item.status}`}>{statusLabels[item.status]||item.status}</span><h3>{item.name}</h3><p>{item.locality} · {item.member_count} membri activi · {item.verification_status}</p></div><div><Link href={`/cont/afaceri/${item.id}`}>Deschide</Link><BusinessAdminActions id={item.id} verified={item.verification_status==="verified"} status={item.status}/></div></article>)}</div></>}
  else if(section==="continut"){
    if(path[1]==="nou"){const bs=await db.prepare("SELECT id,name FROM businesses WHERE deleted_at IS NULL ORDER BY name").all<any>();content=<><AdminTitle title="Conținut nou" copy="Administratorii pot crea orice tip, apoi îl pot publica prin fluxul de moderare."/><ContentEditor businesses={bs.results} admin/></>}
    else if(path[1]&&path[2]){const item=await getContentForEditor(account,Number(path[2]));const bs=await db.prepare("SELECT id,name FROM businesses WHERE deleted_at IS NULL ORDER BY name").all<any>();content=<><AdminTitle title="Editează conținut" copy="Modificările folosesc control optimist al versiunii."/><ContentEditor initial={item as never} businesses={bs.results} admin/>{item&&<>{item.status!=="soft_deleted"&&<ContentAction id={item.id} action="duplicate" label="Duplică drept ciornă" icon="copy"/>}<AdminContentActions id={item.id} status={item.status} featured={Boolean(item.featured)}/></>}{item?.status==="soft_deleted"&&account.globalRole==="platform_owner"&&<PermanentDelete id={item.id} title={item.title}/>}</>}
    else{const rows=await db.prepare("SELECT c.*,u.display_name author_name,b.name business_name FROM content_records c LEFT JOIN users u ON u.id=c.owner_user_id LEFT JOIN businesses b ON b.id=c.business_id ORDER BY c.updated_at DESC LIMIT 1000").all<any>();content=<><AdminTitle title="Conținut" copy="Căutare, filtre de tip și stare, sortare și paginare pentru toate materialele persistente."/><ContentList items={rows.results} admin/></>}
  }
  else if(section==="utilizatori"){if(path[1]){const user=await db.prepare("SELECT * FROM users WHERE id=?").bind(Number(path[1])).first<any>();if(!user)notFound();const [owned,memberships,history]=await Promise.all([db.prepare("SELECT id,title,type,status,updated_at FROM content_records WHERE owner_user_id=? ORDER BY updated_at DESC LIMIT 50").bind(user.id).all<any>(),db.prepare("SELECT b.name,bm.membership_role,bm.membership_status FROM business_memberships bm JOIN businesses b ON b.id=bm.business_id WHERE bm.user_id=?").bind(user.id).all<any>(),db.prepare("SELECT rh.*,u.display_name changed_by_name FROM role_history rh LEFT JOIN users u ON u.id=rh.changed_by WHERE rh.user_id=? ORDER BY rh.created_at DESC").bind(user.id).all<any>()]);content=<><AdminTitle title={user.display_name} copy={`${user.email} · ${roleLabel(user.global_role)}`}/><section className="admin-panel"><UserActions id={user.id} role={user.global_role} status={user.account_status} platformOwner={account.globalRole==="platform_owner"}/><h2>Afacerile utilizatorului</h2>{memberships.results.map((row:any)=><p key={row.name}>{row.name} · {row.membership_role} · {row.membership_status}</p>)}<h2>Conținut recent</h2>{owned.results.map((row:any)=><p key={row.id}><Link href={`/admin/continut/${row.type}/${row.id}`}>{row.title}</Link> · {row.status}</p>)}<h2>Istoric roluri</h2>{history.results.map((row:any)=><p key={row.id}>{row.previous_role} → {row.new_role} · {row.changed_by_name||"Sistem"}</p>)}</section></>}else{const rows=await db.prepare("SELECT id,email,display_name,global_role,account_status,created_at,last_login_at FROM users ORDER BY created_at DESC LIMIT 200").all<any>();content=<><AdminTitle title="Utilizatori" copy="Rolurile administrative pot fi gestionate numai de proprietarul platformei."/><div className="admin-stack">{rows.results.map(user=><article className="admin-review" key={user.id}><h2><Link href={`/admin/utilizatori/${user.id}`}>{user.display_name}</Link></h2><p>{user.email} · {roleLabel(user.global_role)} · {user.account_status}</p><small>Ultima conectare: {user.last_login_at}</small><UserActions id={user.id} role={user.global_role} status={user.account_status} platformOwner={account.globalRole==="platform_owner"}/></article>)}</div></>}}
  else if(section==="categorii"){const rows=await db.prepare("SELECT c.*,(SELECT COUNT(*) FROM businesses b WHERE b.category_id=c.id)+(SELECT COUNT(*) FROM events e WHERE e.category_id=c.id)+(SELECT COUNT(*) FROM posts p WHERE p.category_id=c.id) usage_count FROM categories c ORDER BY c.type,c.name").all<any>();content=<><AdminTitle title="Categorii" copy="Taxonomia folosită de editoare și listări."/><CategoryCreate/><div className="management-list">{rows.results.map(row=><article className="management-row" key={row.id}><div><small>{row.type}</small><h3>{row.name}</h3><p>{row.usage_count} materiale asociate</p></div><CategoryActions id={row.id} name={row.name}/></article>)}</div></>}
  else if(section==="media"){const rows=await db.prepare(`SELECT m.*,u.display_name owner_name,b.name business_name,(CASE WHEN m.content_id IS NULL THEN 0 ELSE 1 END)+(SELECT COUNT(*) FROM site_content_entries e WHERE e.draft_json LIKE '%"mediaId":'||m.id||'%' OR e.published_json LIKE '%"mediaId":'||m.id||'%')+(SELECT COUNT(*) FROM site_content_revisions r WHERE r.snapshot LIKE '%"mediaId":'||m.id||'%') usage_count FROM media_assets m LEFT JOIN users u ON u.id=m.owner_user_id LEFT JOIN businesses b ON b.id=m.business_id WHERE m.media_status!='soft_deleted' ORDER BY m.created_at DESC LIMIT 200`).all<any>();content=<><AdminTitle title="Biblioteca media" copy="Grilă vizuală, căutare, aprobare, atribuire, înlocuire sigură și referințe protejate."/><AdminMediaLibrary items={rows.results}/></>}
  else if(section==="raportari"){const rows=await db.prepare("SELECT * FROM content_reports ORDER BY created_at DESC LIMIT 200").all<any>();content=<><AdminTitle title="Raportări" copy="Sesizări despre informații incorecte sau conținut problematic."/><div className="management-list">{rows.results.map(row=><article className="management-row" key={row.id}><div><span className="status-pill">{row.status}</span><h3>{row.entity_type||"Raportare generală"} #{row.entity_id||"—"}</h3><p>{row.reason}</p><time>{row.created_at}</time></div><ReportActions id={row.id} status={row.status}/></article>)}</div></>}
  else if(section==="audit"){const rows=await db.prepare("SELECT a.*,u.display_name actor_name FROM audit_logs a LEFT JOIN users u ON u.id=a.actor_user_id ORDER BY a.created_at DESC LIMIT 300").all<any>();content=<><AdminTitle title="Istoric audit" copy="Jurnal operațional doar în citire. Nu există acțiuni de ștergere."/><div className="audit-list">{rows.results.map(row=><div key={row.id}><strong>{row.actor_name||"Sistem"}</strong><span>{row.action}</span><small>{row.entity_type} #{row.entity_id||"—"} · {row.created_at}</small></div>)}</div></>}
  else if(section==="promovari"){const rows=await db.prepare("SELECT * FROM promoted_placements ORDER BY starts_at DESC LIMIT 200").all<any>();content=<><AdminTitle title="Promovări" copy="Etichetele promovate sunt administrate separat de proprietarii afacerilor."/><PromotionCreate/><div className="management-list">{rows.results.map(row=><article className="management-row" key={row.id}><div><span className="status-pill">{row.status}</span><h3>{row.entity_type} #{row.entity_id}</h3><p>{row.tier} · {row.starts_at} — {row.ends_at}</p></div><PromotionActions id={row.id} status={row.status}/></article>)}</div></>}
  else if(section==="date-demonstrative"&&demoEnabled){const initial=await getDemoDataStatus(account);content=<><AdminTitle title="Date demonstrative" copy="Generator determinist, control explicit al vizibilității și curățare verificată pentru testarea platformei complete."/><DemoDataAdmin initial={initial}/></>}
  else if(section==="setari")content=<><AdminTitle title="Setări platformă" copy="Configurații protejate și retenție."/><section className="admin-panel"><h2>Roluri și bootstrap</h2><p>Adresa configurată în mediul securizat este folosită numai pentru primul proprietar al platformei. După persistență, rolurile se gestionează din baza de date.</p><h2>Retenție</h2><p>Ștergerea permanentă este limitată proprietarului platformei și verifică perioada de retenție. Auditul nu este șters.</p></section></>;
  else content=<Empty title="Secțiune indisponibilă."/>;
  return <section className="admin-shell"><aside><div className="logo"><span>Blaj</span><b>Azi</b></div><p>Administrare</p><nav>{nav.map(([pattern,href,label,Icon])=><Link className={pattern.test(section)?"active":""} href={href} key={href}><Icon/>{label}</Link>)}</nav><Link href="/deconectare"><LogOut/>Deconectare</Link></aside><details className="admin-mobile-nav"><summary><Menu/> Meniu administrare</summary><nav>{nav.map(([,href,label])=><Link href={href} key={href}>{label}</Link>)}</nav></details><div className="admin-content">{content}</div></section>;
  async function count(sql:string){return (await db.prepare(sql).first<{count:number}>())?.count||0}
}
function AdminTitle({title,copy,action}:{title:string;copy:string;action?:React.ReactNode}){return <header className="admin-title"><div><p className="eyebrow">Administrare Blaj Azi</p><h1>{title}</h1><p>{copy}</p></div>{action}</header>}
function Empty({title}:{title:string}){return <div className="management-empty"><h2>{title}</h2></div>}
function roleLabel(role:string){return role==="business_owner"?"Proprietar de afacere":role==="admin"?"Administrator":role==="platform_owner"?"Proprietar platformă":"Utilizator"}
