"use client";

import { AlertTriangle, Database, Eye, EyeOff, RefreshCw, Trash2 } from "lucide-react";
import { useState } from "react";
import { DEMO_DELETE_CONFIRMATION, type DemoVisibility } from "../demo-data";

type Status={
  generatorVersion:string;visibility:DemoVisibility;expectedTotal:number;expectedMedia:number;actualTotal:number;mediaCount:number;orphanObjectCount:number;protectedUnownedDemoCount:number;
  matrix:Array<{type:string;route:string;recordsPerCategory:number;expectedCount:number;imagePath:string;categories:Array<{label:string;source:string}>}>;
  byType:Record<string,number>;byCategory:Record<string,number>;batches:Array<{id:string;status:string;generatorVersion:string;generatedAt:string|null;deletedAt:string|null;contentCount:number;mediaCount:number;errorSummary:string|null}>;
  warnings:string[];canGenerate:boolean;canDelete:boolean;
};
type Preview={previewToken:string;batchIds:string[];batchCount:number;itemCount:number;contentRows:number;domainRows:number;mediaRows:number;revisionRows:number;moderationRows:number;r2Keys:number;protectedReal:number;protectedUnownedDemo:number;allTargetsProven:boolean;expiresInMinutes:number};

export function DemoDataAdmin({initial}:{initial:Status}){
  const [status,setStatus]=useState(initial);const [visibility,setVisibility]=useState<DemoVisibility>(initial.visibility);const [refreshExisting,setRefreshExisting]=useState(true);const [preview,setPreview]=useState<Preview|null>(null);const [confirmation,setConfirmation]=useState("");const [acknowledged,setAcknowledged]=useState(false);const [busy,setBusy]=useState<"generate"|"preview"|"delete"|"refresh"|null>(null);const [message,setMessage]=useState("");const [error,setError]=useState("");
  async function request<T>(url:string,init?:RequestInit){const response=await fetch(url,init);const data=await response.json() as T&{error?:string};if(!response.ok)throw new Error(data.error||"Operația nu a putut fi finalizată.");return data}
  async function reload(){const next=await request<Status>("/api/admin/demo-data");setStatus(next);setVisibility(next.visibility);return next}
  async function generate(){setBusy("generate");setMessage("");setError("");setPreview(null);try{const result=await request<{created:number;updated:number;unchanged:number;total:number;visibility:DemoVisibility}>("/api/admin/demo-data/generate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({generatorVersion:status.generatorVersion,visibility,refreshExisting})});await reload();setMessage(`Lot finalizat: ${result.created} create, ${result.updated} actualizate, ${result.unchanged} neschimbate; ${result.total} înregistrări în manifest.`)}catch(reason){setError(reason instanceof Error?reason.message:"Generarea a eșuat.")}finally{setBusy(null)}}
  async function buildPreview(){setBusy("preview");setMessage("");setError("");setConfirmation("");setAcknowledged(false);try{setPreview(await request<Preview>("/api/admin/demo-data/delete-preview",{method:"POST",headers:{"content-type":"application/json"},body:"{}"}))}catch(reason){setError(reason instanceof Error?reason.message:"Previzualizarea a eșuat.")}finally{setBusy(null)}}
  async function remove(){if(!preview)return;setBusy("delete");setMessage("");setError("");try{const result=await request<{deletedContent:number;deletedMedia:number;deletedR2:number;r2Failures:string[];byType:Record<string,number>;byCategory:Record<string,number>;protectedReal:number;protectedUnownedDemo:number;reminder:string}>("/api/admin/demo-data",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({confirmation,previewToken:preview.previewToken,batchIds:preview.batchIds})});await reload();setPreview(null);setConfirmation("");setAcknowledged(false);const types=Object.entries(result.byType).map(([type,count])=>`${type}: ${count}`).join(", ");const categories=Object.entries(result.byCategory).map(([category,count])=>`${category}: ${count}`).join(", ");setMessage(`Curățare finalizată: ${result.deletedContent} înregistrări (${types}); pe categorii: ${categories}. Au fost eliminate ${result.deletedMedia} metadate media și ${result.deletedR2} obiecte R2. Protejate: ${result.protectedReal} înregistrări reale și ${result.protectedUnownedDemo} exemple vechi fără lot. Vizibilitatea demo este ascunsă. ${result.reminder}`)}catch(reason){setError(reason instanceof Error?reason.message:"Curățarea a eșuat.")}finally{setBusy(null)}}
  async function refresh(){setBusy("refresh");setError("");try{await reload();setMessage("Starea a fost actualizată.")}catch(reason){setError(reason instanceof Error?reason.message:"Starea nu a putut fi citită.")}finally{setBusy(null)}}
  const deletable=Boolean(preview?.allTargetsProven&&acknowledged&&confirmation===DEMO_DELETE_CONFIRMATION&&!busy);
  return <div className="demo-admin">
    <section className="demo-admin-summary" aria-labelledby="demo-status-title"><div><h2 id="demo-status-title">Stare și acoperire</h2><p>Versiune generator: <code>{status.generatorVersion}</code></p></div><button className="button button-outline" onClick={refresh} disabled={Boolean(busy)}><RefreshCw aria-hidden="true"/> {busy==="refresh"?"Se actualizează…":"Actualizează starea"}</button><dl><div><dt>Înregistrări</dt><dd>{status.actualTotal} / {status.expectedTotal}</dd></div><div><dt>Imagini</dt><dd>{status.mediaCount} / {status.expectedMedia}</dd></div><div><dt>Vizibilitate publică</dt><dd>{status.visibility==="public"?"Activă":"Ascunsă"}</dd></div><div><dt>Obiecte R2 orfane</dt><dd>{status.orphanObjectCount}</dd></div></dl></section>
    {(status.warnings.length>0||status.protectedUnownedDemoCount>0)&&<aside className="demo-warning"><AlertTriangle aria-hidden="true"/><div><h2>Avertismente de siguranță</h2>{status.warnings.map(item=><p key={item}>{item}</p>)}</div></aside>}
    <section className="admin-panel demo-generator"><h2>Generează sau reia lotul</h2><p>Operația este idempotentă. Fiecare combinație tip/categorie primește exact două exemple și o imagine validată, marcate explicit ca demonstrative.</p><fieldset><legend>Vizibilitate după generare</legend><label><input type="radio" name="demo-visibility" checked={visibility==="hidden"} onChange={()=>setVisibility("hidden")}/><EyeOff aria-hidden="true"/><span><strong>Ascunsă public</strong><small>Recomandat pentru pregătire și QA.</small></span></label><label><input type="radio" name="demo-visibility" checked={visibility==="public"} onChange={()=>setVisibility("public")}/><Eye aria-hidden="true"/><span><strong>Vizibilă public</strong><small>Numai loturile active deținute de manifest devin vizibile.</small></span></label></fieldset><label className="check-row"><input type="checkbox" checked={refreshExisting} onChange={event=>setRefreshExisting(event.target.checked)}/>Reîmprospătează înregistrările existente dacă manifestul sau datele relative s-au schimbat.</label><button className="button" disabled={Boolean(busy)||!status.canGenerate} onClick={generate}><Database aria-hidden="true"/>{busy==="generate"?"Se generează…":"Generează datele demonstrative"}</button></section>
    <section className="admin-panel demo-matrix"><h2>Matricea canonică</h2><p>{status.expectedTotal} înregistrări și {status.expectedMedia} imagini așteptate. Categoriile marcate „DB” provin din taxonomia persistentă; celelalte există numai în manifestul demo.</p>{Object.keys(status.byType).length>0&&<div className="demo-actual-counts" aria-label="Numere active pe tip și categorie"><div><h3>Active pe tip</h3>{Object.entries(status.byType).map(([key,count])=><span key={key}><code>{key}</code>: {count}</span>)}</div><div><h3>Active pe categorie</h3>{Object.entries(status.byCategory).map(([key,count])=><span key={key}><code>{key}</code>: {count}</span>)}</div></div>}<div className="demo-table-wrap"><table><thead><tr><th>Tip</th><th>Rută</th><th>Categorii</th><th>Exemple</th><th>Imagine</th></tr></thead><tbody>{status.matrix.map(row=><tr key={row.type}><th scope="row"><code>{row.type}</code></th><td>{row.route}</td><td>{row.categories.map(category=><span className="demo-category" key={category.label}>{category.label} <small>{category.source==="database"?"DB":"demo"}</small></span>)}</td><td>{row.expectedCount} ({row.recordsPerCategory}/categorie)</td><td><code>{row.imagePath}</code></td></tr>)}</tbody></table></div></section>
    <section className="admin-panel demo-batches"><h2>Loturi și audit</h2>{status.batches.length?<div className="management-list">{status.batches.map(batch=><article className="management-row" key={batch.id}><div><span className={`status-pill status-${batch.status}`}>{batch.status}</span><h3>{batch.id}</h3><p>{batch.contentCount} înregistrări · {batch.mediaCount} imagini · {batch.generatedAt||"negenerat"}</p>{batch.errorSummary&&<small>{batch.errorSummary}</small>}</div></article>)}</div>:<p>Nu există încă niciun lot generat.</p>}</section>
    <section className="admin-panel demo-danger"><h2><Trash2 aria-hidden="true"/> Curățare sigură</h2><p>Curățarea elimină numai rândurile și obiectele dovedite prin manifestul lotului. Conținutul real și datele demo vechi, fără lot, sunt protejate.</p><button className="danger-action" disabled={Boolean(busy)||!status.canDelete} onClick={buildPreview}>{busy==="preview"?"Se verifică…":"Previzualizează exact ce va fi șters"}</button>{preview&&<div className="demo-delete-preview"><h3>Previzualizare valabilă {preview.expiresInMinutes} minute</h3><dl><div><dt>Loturi</dt><dd>{preview.batchCount}</dd></div><div><dt>Conținut</dt><dd>{preview.contentRows}</dd></div><div><dt>Rânduri pe tip</dt><dd>{preview.domainRows}</dd></div><div><dt>Media / R2</dt><dd>{preview.mediaRows} / {preview.r2Keys}</dd></div><div><dt>Revizii / moderări</dt><dd>{preview.revisionRows} / {preview.moderationRows}</dd></div><div><dt>Rânduri reale protejate</dt><dd>{preview.protectedReal}</dd></div><div><dt>Demo vechi protejate</dt><dd>{preview.protectedUnownedDemo}</dd></div></dl><label className="check-row"><input type="checkbox" checked={acknowledged} onChange={event=>setAcknowledged(event.target.checked)}/>Am verificat previzualizarea și înțeleg că operația nu poate fi anulată.</label><label>Fraza exactă de confirmare<input value={confirmation} onChange={event=>setConfirmation(event.target.value)} autoComplete="off" placeholder={DEMO_DELETE_CONFIRMATION}/></label><button className="danger-action" disabled={!deletable} onClick={remove}>{busy==="delete"?"Se curăță…":"Șterge exclusiv loturile demonstrate"}</button></div>}</section>
    <div className="demo-live" aria-live="polite" aria-atomic="true">{message&&<p className="success-message">{message}</p>}{error&&<p role="alert" className="error-message">{error}</p>}</div>
  </div>
}
