import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Bell, BriefcaseBusiness, FileText, Home, Plus, Settings, UserRound } from "lucide-react";
import { getRuntimeDb } from "../../../db/runtime";
import { getContentForEditor, listMyContent } from "../../server/content";
import { requireAccountForPage, requireBusinessMembership } from "../../server/platform";
import { BusinessHoursManager, BusinessMediaManager, BusinessRegistrationForm, ClaimBusinessForm, ContentEditor, ContentList, InvitationAction, NotificationActions, statusLabels, TeamManager } from "../../ui/Management";

export const metadata: Metadata = { title: "Contul meu", robots: { index: false, follow: false } };
export const dynamic = "force-dynamic";

export default async function AccountPage({ params, searchParams }: { params: Promise<{ path?: string[] }>; searchParams: Promise<{ acces?: string }> }) {
  const path = (await params).path || [];
  const returnTo = `/cont${path.length ? `/${path.join("/")}` : ""}`;
  const account = await requireAccountForPage(returnTo);
  const db = getRuntimeDb();
  const businesses = await db.prepare("SELECT b.id,b.name,b.slug,b.status,b.verification_status,b.locality,b.description,b.version,bm.membership_role FROM business_memberships bm JOIN businesses b ON b.id=bm.business_id WHERE bm.user_id=? AND bm.membership_status='active' AND b.deleted_at IS NULL ORDER BY b.name").bind(account.id).all<{ id:number; name:string; slug:string; status:string; verification_status:string; locality:string; description:string|null; version:number; membership_role:string }>();
  let content: React.ReactNode;

  if (!path.length) {
    const counts = await db.prepare("SELECT status,COUNT(*) count FROM content_records WHERE owner_user_id=? AND deleted_at IS NULL GROUP BY status").bind(account.id).all<{ status:string; count:number }>();
    const count = Object.fromEntries(counts.results.map(row => [row.status,row.count]));
    const notifications = await db.prepare("SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 4").bind(account.id).all<{ id:number;title:string;message:string;created_at:string;read_at:string|null;href:string|null }>();
    content = <><header className="account-heading"><p className="eyebrow">Contul meu</p><h1>Bine ai venit, {account.displayName}</h1><p>{roleLabel(account.globalRole)} · Aici vezi ce ai de făcut în continuare.</p></header><div className="account-stats">{[["Ciorne",count.draft||0],["În verificare",count.pending_review||0],["Necesită modificări",count.needs_changes||0],["Programate",count.scheduled||0],["Publicate",count.published||0],["Expirate",count.expired||0],["Arhivate",count.archived||0]].map(([label,value])=><article key={label}><strong>{value}</strong><span>{label}</span></article>)}</div><div className="account-columns"><section className="account-panel"><div className="panel-heading"><h2>Acțiuni rapide</h2></div><div className="quick-actions"><Link href="/cont/continut/nou"><Plus /> Creează conținut</Link><Link href="/cont/revendica-afacere"><BriefcaseBusiness /> Revendică o afacere</Link><Link href="/cont/afaceri/noua"><Plus /> Înregistrează o afacere</Link></div></section><section className="account-panel"><div className="panel-heading"><h2>Notificări recente</h2><Link href="/cont/notificari">Vezi toate</Link></div>{notifications.results.map(note=><Link className="notification-row" href={note.href||"/cont/notificari"} key={note.id}><Bell/><span><strong>{note.title}</strong><small>{note.message}</small></span></Link>)}{!notifications.results.length&&<p>Nu ai notificări încă.</p>}</section></div></>;
  } else if (path[0] === "continut") {
    if (path[1] === "nou") content = <><PageTitle title="Conținut nou" copy="Salvează o ciornă, verifică previzualizarea și trimite materialul când este pregătit." /><ContentEditor businesses={businesses.results} /></>;
    else if (path[1]) { let item;try{item=await getContentForEditor(account, Number(path[1]))}catch{notFound()} content = item ? <><PageTitle title="Editează conținutul" copy="Starea și următoarea acțiune sunt mereu afișate. Versiunea publicată rămâne neschimbată cât timp o revizie este verificată." /><ContentEditor initial={item as never} businesses={businesses.results} /></> : <PageTitle title="Conținut indisponibil" copy="Materialul nu există sau nu îl poți administra." />; }
    else { const items = await listMyContent(account); content = <><PageTitle title="Conținutul meu" copy="Ciorne, trimiteri, feedback și materiale publicate într-un singur loc." /><ContentList items={items.results as never} /></>; }
  } else if (path[0] === "profil") {
    content = <><PageTitle title="Profil" copy="Identitatea contului este verificată pe server la fiecare acces." /><section className="account-panel profile-card"><div className="large-avatar">{initials(account.displayName)}</div><dl><div><dt>Nume</dt><dd>{account.displayName}</dd></div><div><dt>E-mail</dt><dd>{account.email}</dd></div><div><dt>Rol</dt><dd>{roleLabel(account.globalRole)}</dd></div><div><dt>Cont creat</dt><dd>{new Intl.DateTimeFormat("ro-RO").format(new Date(account.createdAt))}</dd></div></dl></section></>;
  } else if (path[0] === "notificari") {
    const notes = await db.prepare("SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 200").bind(account.id).all<{id:number;title:string;message:string;href:string|null;read_at:string|null;created_at:string}>();
    content = <><PageTitle title="Notificări" copy="Decizii de moderare, invitații și schimbări importante." action={<NotificationActions />} /><div className="management-list">{notes.results.map(note=><Link className={`management-row ${note.read_at?"":"unread"}`} href={note.href||"#"} key={note.id}><div><span className="status-pill">{note.read_at?"Citită":"Nouă"}</span><h3>{note.title}</h3><p>{note.message}</p><time>{note.created_at}</time></div></Link>)}</div></>;
  } else if (path[0] === "cereri") {
    const claims = await db.prepare("SELECT bc.*,b.name business_name FROM business_claims bc JOIN businesses b ON b.id=bc.business_id WHERE bc.requester_user_id=? ORDER BY bc.submitted_at DESC").bind(account.id).all<{id:number;business_name:string;status:string;reviewer_note:string|null;submitted_at:string}>();
    const invites = await db.prepare("SELECT bm.id,b.name business_name,bm.membership_role FROM business_memberships bm JOIN businesses b ON b.id=bm.business_id WHERE bm.user_id=? AND bm.membership_status='invited'").bind(account.id).all<{id:number;business_name:string;membership_role:string}>();
    content = <><PageTitle title="Cereri și invitații" copy="Urmărește revendicările și răspunde invitațiilor de echipă." />{invites.results.map(invite=><article className="request-card" key={invite.id}><div><span className="status-pill">Invitație</span><h3>{invite.business_name}</h3><p>Rol propus: {invite.membership_role === "owner"?"Proprietar":"Manager"}</p></div><InvitationAction membershipId={invite.id}/></article>)}{claims.results.map(claim=><article className="request-card" key={claim.id}><div><span className={`status-pill status-${claim.status}`}>{statusLabels[claim.status]||claim.status}</span><h3>{claim.business_name}</h3><p>{claim.reviewer_note||"Cererea este analizată de echipa de moderare."}</p><time>{claim.submitted_at}</time></div></article>)}{!claims.results.length&&!invites.results.length&&<div className="management-empty"><h3>Nicio cerere activă</h3><Link className="button" href="/cont/revendica-afacere">Revendică o afacere</Link></div>}</>;
  } else if (path[0] === "revendica-afacere") {
    const publicBusinesses = await db.prepare("SELECT id,name FROM businesses WHERE status='published' AND visibility='public' AND deleted_at IS NULL ORDER BY name").all<{id:number;name:string}>();
    content = <><PageTitle title="Revendică o afacere" copy="Potrivirea adresei de e-mail nu este suficientă. Un administrator verifică dovada și relația cu afacerea." /><ClaimBusinessForm businesses={publicBusinesses.results} /></>;
  } else if (path[0] === "afaceri") {
    if (path[1] === "noua") content = <><PageTitle title="Înregistrează o afacere" copy="Profilul intră în verificare. După aprobare vei primi calitatea de proprietar și acces la administrare." /><BusinessRegistrationForm /></>;
    else if (!path[1]) content = <><PageTitle title="Afacerea mea" copy="Poți administra doar afacerile unde ai un membru activ." action={<Link className="button" href="/cont/afaceri/noua">Afacere nouă</Link>} /><div className="business-account-grid">{businesses.results.map(business=><article className="account-panel" key={business.id}><span className={`status-pill status-${business.status}`}>{business.status === "published"?"Publicată":statusLabels[business.status]||business.status}</span><h2>{business.name}</h2><p>{business.locality} · {business.membership_role === "owner"?"Proprietar":"Manager"}</p><Link className="button button-outline" href={`/cont/afaceri/${business.id}`}>Administrează</Link></article>)}</div>{!businesses.results.length&&<div className="management-empty"><h3>Nu administrezi nicio afacere încă</h3><p>Poți revendica un profil existent sau înregistra o afacere nouă.</p></div>}</>;
    else {
      const businessId=Number(path[1]); try{await requireBusinessMembership(account,businessId)}catch{notFound()} const business=businesses.results.find(item=>item.id===businessId); if(!business) notFound();
      const area=path[2]||"prezentare"; const businessNav=<nav className="business-tabs">{[["prezentare","Prezentare"],["editeaza","Profil"],["program","Program"],["fotografii","Fotografii"],["oferte","Oferte"],["evenimente","Evenimente"],["joburi","Joburi"],["meniul-zilei","Meniul zilei"],["postari","Postări"],["echipa","Echipă"],["statistici","Statistici"]].map(([href,label])=><Link className={area===href?"active":""} key={href} href={`/cont/afaceri/${businessId}/${href}`}>{label}</Link>)}</nav>;
      if(["continut","oferte","evenimente","joburi","meniul-zilei","postari"].includes(area)){const typeByArea:Record<string,string[]>={oferte:["offer"],evenimente:["event"],joburi:["job"],"meniul-zilei":["daily_menu","restaurant"],postari:["business_update","community_post","local_story"]};const items=await listMyContent(account,"","","");const visible=items.results.filter(item=>item.business_id===businessId&&(!typeByArea[area]||typeByArea[area].includes(item.type)));content=<><PageTitle title={`${business.name} — ${area==="continut"?"Conținut":businessNavLabel(area)}`} copy="Creează și administrează numai materialele legate de această afacere." action={<Link className="button" href={`/cont/continut/nou?business=${businessId}`}>Creează</Link>}/>{businessNav}<ContentList items={visible as never}/></>}
      else if(area==="echipa"){const team=await db.prepare("SELECT bm.id,bm.membership_role,bm.membership_status,bm.invite_email,u.display_name,u.email FROM business_memberships bm LEFT JOIN users u ON u.id=bm.user_id WHERE bm.business_id=? ORDER BY bm.invited_at").bind(businessId).all();content=<><PageTitle title={`${business.name} — Echipă`} copy="Proprietarii pot invita manageri. Fiecare persoană trebuie să accepte invitația." />{businessNav}<TeamManager businessId={businessId} items={team.results as never}/></>}
      else if(area==="statistici"){const totals=await db.prepare("SELECT status,COUNT(*) count FROM content_records WHERE business_id=? GROUP BY status").bind(businessId).all<{status:string;count:number}>();content=<><PageTitle title={`${business.name} — Statistici`} copy="Contoarele disponibile acum provin din conținutul persistent al afacerii." />{businessNav}<div className="account-stats">{totals.results.map(row=><article key={row.status}><strong>{row.count}</strong><span>{statusLabels[row.status]||row.status}</span></article>)}</div></>}
      else if(area==="program"){const hours=await db.prepare("SELECT weekday,opens_at,closes_at,closed FROM business_hours WHERE business_id=? ORDER BY weekday").bind(businessId).all<{weekday:number;opens_at:string|null;closes_at:string|null;closed:number}>();content=<><PageTitle title={`${business.name} — Program`} copy="Programul este persistent și poate fi actualizat doar de echipa autorizată."/>{businessNav}<BusinessHoursManager businessId={businessId} items={hours.results}/></>}
      else if(area==="fotografii"){const [media,record]=await Promise.all([db.prepare("SELECT id,title,original_filename,alt_text,approval_status,media_status FROM media_assets WHERE business_id=? AND media_status='active' ORDER BY created_at DESC").bind(businessId).all<{id:number;title:string|null;original_filename:string|null;alt_text:string|null;approval_status:string;media_status:string}>(),db.prepare("SELECT id FROM content_records WHERE type='business' AND entity_id=? AND deleted_at IS NULL").bind(businessId).first<{id:number}>()]);content=<><PageTitle title={`${business.name} — Fotografii`} copy="Imaginile intră în aprobarea bibliotecii media înainte de publicare."/>{businessNav}<BusinessMediaManager businessId={businessId} contentId={record?.id} items={media.results}/></>}
      else if(area==="editeaza"){const record=await db.prepare("SELECT id FROM content_records WHERE type='business' AND entity_id=? AND deleted_at IS NULL").bind(businessId).first<{id:number}>();const item=record?await getContentForEditor(account,record.id):null;content=<><PageTitle title={`${business.name} — Profil`} copy="Modificările unui profil publicat păstrează versiunea live până la aprobarea reviziei."/>{businessNav}{item?<ContentEditor initial={item as never} businesses={businesses.results}/>:<p>Profilul nu are încă un material editabil.</p>}</>}
      else content=<><PageTitle title={business.name} copy={`${business.locality} · ${business.verification_status === "verified"?"Afacere verificată":"Neverificată"}`} />{businessNav}<section className="account-panel"><h2>Prezentare</h2><p>{business.description||"Completează profilul și trimite modificările spre verificare."}</p><Link className="button" href={`/cont/continut/nou?business=${businessId}`}>Creează conținut pentru afacere</Link></section></>;
    }
  } else if (path[0] === "setari") content = <><PageTitle title="Setări" copy="Preferințe de cont și confidențialitate." /><section className="account-panel"><h2>Notificări</h2><p>Notificările în aplicație sunt active. Trimiterea prin e-mail nu este configurată și nu este prezentată ca funcțională.</p><h2>Închiderea contului</h2><p>Pentru solicitări privind datele personale, folosește pagina de contact. Istoricul operațional poate fi anonimizat fără ștergerea auditului.</p></section></>;
  else content = <PageTitle title="Pagină indisponibilă" copy="Revino la pagina principală a contului." />;

  const accessNotice = (await searchParams).acces === "administrare";
  return <section className="account-shell"><aside className="account-sidebar"><Link className="logo" href="/"><span>Blaj</span><b>Azi</b></Link><p>{account.displayName}</p><nav><Link href="/cont"><Home/>Rezumat</Link><Link href="/cont/profil"><UserRound/>Profil</Link><Link href="/cont/continut"><FileText/>Conținutul meu</Link><Link href="/cont/afaceri"><BriefcaseBusiness/>Afacerea mea</Link><Link href="/cont/notificari"><Bell/>Notificări</Link><Link href="/cont/setari"><Settings/>Setări</Link></nav><Link href="/deconectare">Deconectare</Link><Link href="/">Înapoi la site</Link></aside><details className="account-mobile-nav"><summary>Meniu cont</summary><nav><Link href="/cont">Rezumat</Link><Link href="/cont/continut">Conținutul meu</Link><Link href="/cont/afaceri">Afacerea mea</Link><Link href="/cont/notificari">Notificări</Link><Link href="/cont/cereri">Cereri</Link><Link href="/cont/setari">Setări</Link><Link href="/deconectare">Deconectare</Link></nav></details><div className="account-content">{accessNotice && <div className="form-alert form-alert-info" role="status"><strong>Acces administrativ indisponibil.</strong> Contul tău este conectat, dar nu are un rol de administrator.</div>}{content}</div></section>;
}

function PageTitle({title,copy,action}:{title:string;copy:string;action?:React.ReactNode}){return <header className="account-heading"><div><p className="eyebrow">Contul meu</p><h1>{title}</h1><p>{copy}</p></div>{action}</header>}
function roleLabel(role:string){return role==="business_owner"?"Proprietar de afacere":role==="admin"?"Administrator":role==="platform_owner"?"Proprietar platformă":"Utilizator"}
function initials(name:string){return name.split(/\s+/).slice(0,2).map(part=>part[0]?.toUpperCase()).join("")}
function businessNavLabel(area:string){return area==="oferte"?"Oferte":area==="evenimente"?"Evenimente":area==="joburi"?"Joburi":area==="meniul-zilei"?"Meniul zilei":"Postări"}
