"use client";

import { useState } from "react";

export function ModerationActions({ id }: { id:number }) {
  const [note,setNote]=useState(""); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  async function run(action:string){if(["reject","needs_changes"].includes(action)&&!note.trim()){setMessage("Adaugă o notă pentru această decizie.");return}setBusy(true);const response=await fetch("/api/admin/moderation",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id,action,note})});const data=await response.json() as {error?:string};if(response.ok)location.reload();else setMessage(data.error||"Acțiunea nu a putut fi finalizată.");setBusy(false)}
  return <div className="admin-decision"><label>Notă de moderare<textarea value={note} onChange={event=>setNote(event.target.value)} rows={3}/></label><div className="inline-actions"><button disabled={busy} onClick={()=>run("publish")}>Aprobă și publică</button><button disabled={busy} onClick={()=>run("approve")}>Aprobă</button><button disabled={busy} onClick={()=>run("needs_changes")}>Solicită modificări</button><button disabled={busy} className="danger-action" onClick={()=>run("reject")}>Respinge</button></div>{message&&<p className="error-message" role="alert">{message}</p>}</div>;
}

export function ClaimActions({ id }: { id:number }) {
  const [note,setNote]=useState("");const [message,setMessage]=useState("");
  async function run(action:string){const response=await fetch("/api/admin/claims",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id,action,note})});const data=await response.json() as {error?:string};if(response.ok)location.reload();else setMessage(data.error||"Acțiunea nu a reușit.")}
  return <div className="admin-decision"><label>Notă internă / feedback<textarea rows={3} value={note} onChange={event=>setNote(event.target.value)}/></label><div className="inline-actions"><button onClick={()=>run("approve")}>Aprobă</button><button onClick={()=>run("needs_changes")}>Cere informații</button><button className="danger-action" onClick={()=>run("reject")}>Respinge</button></div>{message&&<p className="error-message">{message}</p>}</div>;
}

export function UserActions({ id, role, status, platformOwner }: { id:number;role:string;status:string;platformOwner:boolean }) {
  const [reason,setReason]=useState("");const [message,setMessage]=useState("");
  async function run(payload:Record<string,unknown>){if(!confirm("Confirmi schimbarea acestui cont?"))return;const response=await fetch("/api/admin/users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({userId:id,reason,...payload})});const data=await response.json() as {error?:string};if(response.ok)location.reload();else setMessage(data.error||"Schimbarea nu a reușit.")}
  return <div className="admin-decision"><label>Motiv / notă<input value={reason} onChange={event=>setReason(event.target.value)}/></label><div className="inline-actions"><select aria-label="Rol nou" defaultValue={role} onChange={event=>run({action:"role",role:event.target.value})}><option value="user">Utilizator</option><option value="business_owner">Proprietar de afacere</option>{platformOwner&&<option value="admin">Administrator</option>}{platformOwner&&<option value="platform_owner">Proprietar platformă</option>}</select><button className={status==="active"?"danger-action":""} onClick={()=>run({action:status==="active"?"suspend":"reactivate"})}>{status==="active"?"Suspendă":"Reactivează"}</button></div>{message&&<p className="error-message">{message}</p>}</div>;
}

export function BusinessAdminActions({id,verified,status}:{id:number;verified:boolean;status:string}){const[message,setMessage]=useState("");async function run(action:string){if(!confirm("Confirmi schimbarea profilului de afacere?"))return;const response=await fetch(`/api/admin/businesses/${id}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action})});const data=await response.json() as {error?:string};if(response.ok)location.reload();else setMessage(data.error||"Schimbarea nu a reușit.")}return <div className="inline-actions"><button onClick={()=>run(verified?"unverify":"verify")}>{verified?"Retrage verificarea":"Marchează verificată"}</button><button onClick={()=>run(status==="archived"?"restore":"archive")}>{status==="archived"?"Restaurează":"Arhivează"}</button>{message&&<p className="error-message">{message}</p>}</div>}

export function PermanentDelete({id,title}:{id:number;title:string}){const[confirmText,setConfirmText]=useState("");const[message,setMessage]=useState("");async function run(){const response=await fetch(`/api/admin/content/${id}/permanent-delete`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({confirmation:confirmText})});const data=await response.json() as {error?:string};setMessage(response.ok?"Conținutul eligibil a fost șters permanent.":data.error||"Ștergerea nu a reușit.")}return <div className="delete-guard"><strong>Ștergere permanentă protejată</strong><p>Disponibilă doar după perioada de retenție. Scrie exact titlul materialului.</p><input value={confirmText} onChange={event=>setConfirmText(event.target.value)} placeholder={title}/><button className="danger-action" onClick={run}>Șterge permanent</button>{message&&<p>{message}</p>}</div>}
