"use client";

import { useState } from "react";

export function ModerationActions({ id }: { id:number }) {
  const [note,setNote]=useState(""); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  async function run(action:string){if(["reject","needs_changes"].includes(action)&&!note.trim()){setMessage("Adaugă o notă pentru această decizie.");return}setBusy(true);const response=await fetch("/api/admin/moderation",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id,action,note})});const data=await response.json() as {error?:string};if(response.ok)location.reload();else setMessage(data.error||"Acțiunea nu a putut fi finalizată.");setBusy(false)}
  return <div className="admin-decision"><label>Notă de moderare<textarea value={note} onChange={event=>setNote(event.target.value)} rows={3}/></label><div className="inline-actions"><button disabled={busy} onClick={()=>run("publish")}>Aprobă și publică</button><button disabled={busy} onClick={()=>run("approve")}>Aprobă</button><button disabled={busy} onClick={()=>run("needs_changes")}>Solicită modificări</button><button disabled={busy} className="danger-action" onClick={()=>run("reject")}>Respinge</button></div>{message&&<p className="error-message" role="alert">{message}</p>}</div>;
}

export function ClaimActions({ id }: { id:number }) {
  const [note,setNote]=useState("");const [message,setMessage]=useState("");
  async function run(action:string){const response=await fetch("/api/admin/claims",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id,action,note})});const data=await response.json() as {error?:string};if(response.ok)location.reload();else setMessage(data.error||"Acțiunea nu a reușit.")}
  return <div className="admin-decision"><label>Notă internă / feedback<textarea rows={3} value={note} onChange={event=>setNote(event.target.value)}/></label><div className="inline-actions"><button onClick={()=>run("approve")}>Aprobă</button><button onClick={()=>run("needs_changes")}>Cere informații</button><button className="danger-action" onClick={()=>run("reject")}>Respinge</button></div>{message&&<p className="error-message">{message}</p>}</div>;
}

export function UserActions({ id, role, status, platformOwner }: { id:number;role:string;status:string;platformOwner:boolean }) {
  const [reason,setReason]=useState("");const [message,setMessage]=useState("");
  async function run(payload:Record<string,unknown>){if(!confirm("Confirmi schimbarea acestui cont?"))return;const response=await fetch("/api/admin/users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({userId:id,reason,...payload})});const data=await response.json() as {error?:string};if(response.ok)location.reload();else setMessage(data.error||"Schimbarea nu a reușit.")}
  return <div className="admin-decision"><label>Motiv / notă<input value={reason} onChange={event=>setReason(event.target.value)}/></label><div className="inline-actions"><select aria-label="Rol nou" defaultValue={role} onChange={event=>run({action:"role",role:event.target.value})}><option value="user">Utilizator</option><option value="business_owner">Proprietar de afacere</option>{platformOwner&&<option value="admin">Administrator</option>}{platformOwner&&<option value="platform_owner">Proprietar platformă</option>}</select><button className={status==="active"?"danger-action":""} onClick={()=>run({action:status==="active"?"suspend":"reactivate"})}>{status==="active"?"Suspendă":"Reactivează"}</button></div>{message&&<p className="error-message">{message}</p>}</div>;
}

export function BusinessAdminActions({id,verified,status}:{id:number;verified:boolean;status:string}){const[message,setMessage]=useState("");async function run(action:string){if(!confirm("Confirmi schimbarea profilului de afacere?"))return;const response=await fetch(`/api/admin/businesses/${id}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action})});const data=await response.json() as {error?:string};if(response.ok)location.reload();else setMessage(data.error||"Schimbarea nu a reușit.")}return <div className="inline-actions"><button onClick={()=>run(verified?"unverify":"verify")}>{verified?"Retrage verificarea":"Marchează verificată"}</button><button onClick={()=>run(status==="archived"?"restore":"archive")}>{status==="archived"?"Restaurează":"Arhivează"}</button>{message&&<p className="error-message">{message}</p>}</div>}

export function PermanentDelete({id,title}:{id:number;title:string}){const[confirmText,setConfirmText]=useState("");const[message,setMessage]=useState("");async function run(){const response=await fetch(`/api/admin/content/${id}/permanent-delete`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({confirmation:confirmText})});const data=await response.json() as {error?:string};setMessage(response.ok?"Conținutul eligibil a fost șters permanent.":data.error||"Ștergerea nu a reușit.")}return <div className="delete-guard"><strong>Ștergere permanentă protejată</strong><p>Disponibilă doar după perioada de retenție. Scrie exact titlul materialului.</p><input value={confirmText} onChange={event=>setConfirmText(event.target.value)} placeholder={title}/><button className="danger-action" onClick={run}>Șterge permanent</button>{message&&<p>{message}</p>}</div>}

export function MediaAdminActions({id,status,altText}:{id:number;status:string;altText:string}){const[message,setMessage]=useState("");async function run(action:"approve"|"reject"|"archive"){if(action!=="approve"&&!confirm("Confirmi această acțiune media?"))return;const response=await fetch(`/api/media/${id}`,{method:action==="archive"?"DELETE":"PATCH",headers:{"content-type":"application/json"},body:action==="archive"?undefined:JSON.stringify({action})});const data=await response.json() as{error?:string};if(response.ok)location.reload();else setMessage(data.error||"Acțiunea media nu a reușit.")}async function replace(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const response=await fetch(`/api/media/${id}`,{method:"PUT",body:new FormData(event.currentTarget)});const data=await response.json() as{error?:string};if(response.ok)location.reload();else setMessage(data.error||"Imaginea nu a putut fi înlocuită.")}return <div className="admin-decision"><div className="inline-actions"><button onClick={()=>run("approve")} disabled={status==="approved"}>Aprobă</button><button onClick={()=>run("reject")} disabled={status==="rejected"}>Respinge</button><button onClick={()=>run("archive")}>Arhivează</button></div><form className="media-replace" onSubmit={replace}><label>Înlocuiește fișierul<input name="file" type="file" accept="image/jpeg,image/png,image/webp" required/></label><label>Alt text<input name="altText" defaultValue={altText} required/></label><button>Înlocuiește</button></form>{message&&<p className="error-message">{message}</p>}</div>}

export function MediaCleanupAction(){const[message,setMessage]=useState("");async function run(){if(!confirm("Cureți încărcările abandonate a căror perioadă de retenție a expirat?"))return;const response=await fetch("/api/media",{method:"DELETE"});const data=await response.json() as{removed?:number;error?:string};setMessage(response.ok?`${data.removed||0} fișiere abandonate au fost eliminate.`:data.error||"Curățarea nu a reușit.")}return <div><button className="button button-outline" onClick={run}>Curăță fișiere abandonate</button>{message&&<p role="status">{message}</p>}</div>}

export function CategoryCreate(){const[message,setMessage]=useState("");async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const response=await fetch("/api/admin/categories",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"create",...Object.fromEntries(form)})});const data=await response.json() as{error?:string};if(response.ok)location.reload();else setMessage(data.error||"Categoria nu a putut fi creată.")}return <form className="team-invite" onSubmit={submit}><label>Nume categorie<input name="name" required/></label><label>Tip<select name="type"><option value="business">Afaceri</option><option value="event">Evenimente</option><option value="post">Postări</option><option value="place">Locuri</option></select></label><button className="button">Adaugă</button>{message&&<p className="error-message">{message}</p>}</form>}

export function CategoryActions({id,name}:{id:number;name:string}){const[nextName,setNextName]=useState(name);const[message,setMessage]=useState("");async function request(action:"update"|"delete"){if(action==="delete"&&!confirm(`Ștergi categoria „${name}”?`))return;const response=await fetch("/api/admin/categories",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,id,name:nextName})});const data=await response.json() as{error?:string};if(response.ok)location.reload();else setMessage(data.error||"Categoria nu a putut fi actualizată.")}return <div className="admin-decision"><label>Redenumește<input value={nextName} onChange={event=>setNextName(event.target.value)}/></label><div className="inline-actions"><button onClick={()=>request("update")}>Salvează</button><button className="danger-action" onClick={()=>request("delete")}>Șterge dacă nu este folosită</button></div>{message&&<p className="error-message">{message}</p>}</div>}

export function ReportActions({id,status}:{id:number;status:string}){const[note,setNote]=useState("");const[message,setMessage]=useState("");async function run(action:string){const response=await fetch("/api/admin/reports",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id,action,note})});const data=await response.json() as{error?:string};if(response.ok)location.reload();else setMessage(data.error||"Raportarea nu a putut fi actualizată.")}return <div className="admin-decision"><label>Notă de soluționare<textarea rows={2} value={note} onChange={event=>setNote(event.target.value)}/></label><div className="inline-actions">{status==="new"&&<button onClick={()=>run("assign")}>Preia</button>}<button onClick={()=>run("resolve")}>Rezolvă</button><button onClick={()=>run("dismiss")}>Închide ca nefondată</button></div>{message&&<p className="error-message">{message}</p>}</div>}

export function PromotionCreate(){const[message,setMessage]=useState("");async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const response=await fetch("/api/admin/promotions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"create",...Object.fromEntries(form)})});const data=await response.json() as{error?:string};if(response.ok)location.reload();else setMessage(data.error||"Promovarea nu a putut fi creată.")}return <form className="team-invite" onSubmit={submit}><label>ID conținut publicat<input name="entityId" type="number" min="1" required/></label><label>Nivel<select name="tier"><option value="local">Local</option><option value="featured">Recomandat</option></select></label><label>Începe<input name="startsAt" type="datetime-local" required/></label><label>Se încheie<input name="endsAt" type="datetime-local" required/></label><button className="button">Programează</button>{message&&<p className="error-message">{message}</p>}</form>}

export function PromotionActions({id,status}:{id:number;status:string}){async function run(action:string){if(!confirm("Confirmi schimbarea promovării?"))return;const response=await fetch("/api/admin/promotions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id,action})});if(response.ok)location.reload()}return <div className="inline-actions"><button onClick={()=>run(status==="active"?"pause":"activate")}>{status==="active"?"Pauză":"Activează"}</button><button onClick={()=>run("archive")}>Arhivează</button></div>}

export function AdminContentActions({id,status,featured}:{id:number;status:string;featured:boolean}){const[note,setNote]=useState("");const[scheduledAt,setScheduledAt]=useState("");const[message,setMessage]=useState("");async function run(action:string){if(["archive","restore","restore_deleted","soft_delete"].includes(action)&&!confirm("Confirmi acțiunea asupra acestui material?"))return;const scheduleValue=scheduledAt?new Date(scheduledAt).toISOString():"";const response=await fetch("/api/admin/moderation",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id,action,note,scheduledAt:scheduleValue})});const data=await response.json() as{error?:string};if(response.ok)location.reload();else setMessage(data.error||"Acțiunea nu a reușit.")}return <div className="admin-decision"><label>Notă administrativă<textarea rows={2} value={note} onChange={event=>setNote(event.target.value)}/></label>{!["published","archived","soft_deleted"].includes(status)&&<label>Publică la<input type="datetime-local" value={scheduledAt} onChange={event=>setScheduledAt(event.target.value)}/></label>}<div className="inline-actions">{!["published","soft_deleted"].includes(status)&&<button onClick={()=>run("publish")}>Publică acum</button>}{!["published","archived","soft_deleted"].includes(status)&&<button onClick={()=>run("schedule")}>Programează</button>}{status==="published"&&<button onClick={()=>run("archive")}>Arhivează</button>}{status==="archived"&&<button onClick={()=>run("restore")}>Restaurează</button>}{status==="soft_deleted"&&<button onClick={()=>run("restore_deleted")}>Recuperează drept ciornă</button>}{status==="published"&&<button onClick={()=>run(featured?"unfeature":"feature")}>{featured?"Scoate din recomandate":"Recomandă"}</button>}{status!=="soft_deleted"&&<button className="danger-action" onClick={()=>run("soft_delete")}>Ștergere recuperabilă</button>}</div>{message&&<p className="error-message">{message}</p>}</div>}
