"use client";

import Link from "next/link";
import { ArrowRight, BriefcaseBusiness, CalendarDays, Check, ChevronRight, Clock3, MapPin, Search, Store, Tag, UtensilsCrossed } from "lucide-react";
import type { PublicCatalog } from "../public-types";
import { cmsImageUrl, resolveCmsImage } from "../site-content";
import { useMemo, useState } from "react";

type HomeCopy = Record<string, unknown>;
type QuickCategory = { label: string; href: string; icon: string; visible: boolean };
const icons = { calendar: CalendarDays, restaurant: UtensilsCrossed, services: Store, offers: Tag, jobs: BriefcaseBusiness, children: Check };
const value = (copy: HomeCopy, key: string) => String(copy[key] ?? "");

export function HomeExperience({ catalog, content }: { catalog: PublicCatalog; content: HomeCopy }) {
  const { businesses, events, jobs, offers, places, restaurants } = catalog;
  const [eventFilter, setEventFilter] = useState("Toate");
  const [foodFilter, setFoodFilter] = useState("Toate");
  const shownEvents = useMemo(() => eventFilter === "Toate" ? events : events.filter(event => event.category === eventFilter || eventFilter === "Weekend"), [eventFilter, events]);
  const shownFood = useMemo(() => foodFilter === "Toate" ? restaurants : restaurants.filter(restaurant => restaurant.type.includes(foodFilter) || restaurant.services.includes(foodFilter)), [foodFilter, restaurants]);
  const featuredPlace = places[1] || places[0];
  const today = new Intl.DateTimeFormat("ro-RO", { day: "numeric", month: "long", year: "numeric" }).format(new Date());
  const hero = resolveCmsImage(content.heroImage);
  const editorialConfigured = resolveCmsImage(content.editorialImage);
  const editorial = editorialConfigured.mediaId || editorialConfigured.src ? editorialConfigured : null;
  const quickCategories = (Array.isArray(content.quickCategories) ? content.quickCategories : []) as QuickCategory[];
  const foodFilters = (Array.isArray(content.restaurantFilters) ? content.restaurantFilters : []).map(item => typeof item === "string" ? item : String((item as { value?: string }).value || "")).filter(Boolean);
  return <>
    <section className="hero">
      <img className="hero-image" src={cmsImageUrl(hero)} alt={hero.decorative ? "" : hero.alt} style={{ objectPosition: hero.objectPosition }} width="1600" height="1067" fetchPriority="high" />
      <div className="hero-shade" />
      <div className="hero-content"><p className="kicker">{value(content, "kicker")}</p><h1>{value(content, "titleLine")}<br /><em>{value(content, "emphasizedTitleLine")}</em></h1><p className="hero-copy">{value(content, "intro")}</p><form className="hero-search" action="/cauta" method="get"><Search aria-hidden="true" /><label className="sr-only" htmlFor="hero-query">{value(content, "searchLabel")}</label><input id="hero-query" name="q" placeholder={value(content, "searchPlaceholder")} /><button type="submit">{value(content, "searchButton")}</button></form><div className="hero-actions"><Link className="button" href={value(content, "primaryCtaHref")}>{value(content, "primaryCtaLabel")} <ArrowRight size={18} /></Link><Link className="text-link light" href={value(content, "secondaryCtaHref")}>{value(content, "secondaryCtaLabel")} <ChevronRight size={16} /></Link></div>{hero.showCredit && <ImageCredit image={hero} />}</div>
    </section>
    <section className="category-strip" aria-label="Categorii rapide"><div className="container category-grid">{quickCategories.filter(item => item.visible).map(item => { const Icon = icons[item.icon as keyof typeof icons] || Check; return <Link href={item.href} key={`${item.href}-${item.label}`}><Icon size={20} /><span>{item.label}</span><ChevronRight size={16} /></Link>; })}</div></section>
    <section className="section container"><SectionHead eyebrow={value(content, "eventsEyebrow")} title={value(content, "eventsTitle")} href="/evenimente" link={value(content, "eventsLinkLabel")} />{events.length > 0 && <div className="chips" role="group" aria-label="Filtre evenimente">{["Toate", "Weekend", "Copii", "Cultură", "Comunitate"].map(filter => <button onClick={() => setEventFilter(filter)} className={eventFilter === filter ? "active" : ""} key={filter}>{filter}</button>)}</div>}<div className="event-grid">{shownEvents.slice(0, 3).map((event, index) => <article className={`event-card ${index === 0 ? "event-featured" : ""}`} key={event.id}><div className="event-image"><img src={event.image} alt="" width="640" height="420" loading="lazy" />{event.isDemo && <span className="demo-badge">Conținut demonstrativ</span>}</div><div className="event-body"><div className="meta"><span>{event.category}</span><span>{event.price}</span></div><h3>{event.title}</h3><p><CalendarDays size={17} /> {event.date} · {event.time}</p><p><MapPin size={17} /> {event.place}</p><Link className="card-link" href={`/evenimente/${event.id}`}>Detalii <ArrowRight size={16} /></Link></div></article>)}</div>{shownEvents.length === 0 && <div className="empty-state"><Search /><h3>{value(content, "eventsEmptyTitle")}</h3><p>{value(content, "eventsEmptyDescription")}</p></div>}</section>
    {featuredPlace && <section className="discover-section"><div className="container"><SectionHead eyebrow={value(content, "discoverEyebrow")} title={value(content, "discoverTitle")} href="/descopera-blaj" link={value(content, "discoverLinkLabel")} light /><div className="editorial-grid"><article className="story-main"><img src={editorial ? cmsImageUrl(editorial) : featuredPlace.image} alt={editorial ? (editorial.decorative ? "" : editorial.alt) : featuredPlace.title} style={editorial ? { objectPosition: editorial.objectPosition } : undefined} width="900" height="600" loading="lazy" /><div><p className="kicker">{value(content, "editorialKicker")}</p><h3>{value(content, "editorialTitle")}</h3><p>{value(content, "editorialCopy")}</p><Link className="button button-cream" href={value(content, "editorialCtaHref")}>{value(content, "editorialCtaLabel")}</Link></div></article><div className="story-list">{places.slice(0, 3).map(place => <Link href={`/descopera-blaj/${place.id}`} className="story-row" key={place.id}><img src={place.image} alt="" width="232" height="176" loading="lazy" /><span><small>{place.eyebrow}</small><strong>{place.title}</strong></span><ArrowRight /></Link>)}</div></div><div className="media-links"><Link href="/descopera-blaj#imagini">Vezi Blajul în imagini <ArrowRight /></Link></div></div></section>}
    {businesses.length > 0 && <section className="section container"><SectionHead eyebrow={value(content, "servicesEyebrow")} title={value(content, "servicesTitle")} href="/afaceri-si-servicii" link={value(content, "servicesLinkLabel")} /><div className="business-grid">{businesses.slice(0, 4).map(business => <article className="business-card" key={business.id}>{business.promoted && <span className="promoted">Promovat</span>}<div className="business-mark">{business.name.charAt(0)}</div><p className="eyebrow">{business.category}</p><h3>{business.name}</h3><p><MapPin size={16} /> {business.locality}</p>{business.isDemo && <span className="demo-line">Exemplu demonstrativ</span>}<div className="card-actions"><Link href={`/afaceri-si-servicii/${business.id}`}>Vezi profilul <ArrowRight size={17} /></Link></div></article>)}</div></section>}
    {offers.length > 0 && <section className="section offer-section"><div className="container"><SectionHead eyebrow={value(content, "offersEyebrow")} title={value(content, "offersTitle")} href="/oferte-locale" link={value(content, "offersLinkLabel")} /><div className="offer-grid">{offers.slice(0, 3).map((offer, index) => <article className="offer-card" key={offer.id}><span className="offer-number">0{index + 1}</span>{offer.isDemo && <p className="demo-line">Exemplu demonstrativ</p>}<h3>{offer.title}</h3><p>{offer.business}</p><div className="price">{offer.old && <del>{offer.old}</del>}<strong>{offer.price}</strong></div><p className="offer-until"><Clock3 size={16} /> Valabilă până la {offer.until}</p><Link href={`/oferte-locale/${offer.id}`}>Vezi condițiile <ArrowRight size={16} /></Link></article>)}</div></div></section>}
    {restaurants.length > 0 && <section className="section container"><SectionHead eyebrow={`${value(content, "restaurantsEyebrow")}, ${today}`} title={value(content, "restaurantsTitle")} href="/unde-mancam" link={value(content, "restaurantsLinkLabel")} /><div className="chips">{foodFilters.map(filter => <button onClick={() => setFoodFilter(filter)} className={foodFilter === filter ? "active" : ""} key={filter}>{filter}</button>)}</div><div className="food-list">{shownFood.slice(0, 5).map((restaurant, index) => <article className="food-card" key={restaurant.id}><div className="food-index">{String(index + 1).padStart(2, "0")}</div><div><p className="eyebrow">{restaurant.type}{restaurant.isDemo ? " · Exemplu demonstrativ" : ""}</p><h3>{restaurant.name}</h3><p>{restaurant.dish}</p><small>{restaurant.services}</small></div><strong>{restaurant.price}</strong><Link href={`/unde-mancam/${restaurant.id}`} aria-label={`Detalii ${restaurant.name}`}><ArrowRight /></Link></article>)}</div></section>}
    {jobs.length > 0 && <section className="section jobs-section"><div className="container"><SectionHead eyebrow={value(content, "jobsEyebrow")} title={value(content, "jobsTitle")} href="/locuri-de-munca" link={value(content, "jobsLinkLabel")} light /><div className="job-list">{jobs.slice(0, 4).map(job => <article className="job-row" key={job.id}><div>{job.isDemo && <span className="demo-badge">Exemplu demonstrativ</span>}<h3>{job.title}</h3><p>{job.company} · {job.locality}</p></div><div><small>Program</small><strong>{job.type} · {job.schedule}</strong></div><div><small>Salariu</small><strong>{job.salary}</strong></div><Link href={`/locuri-de-munca/${job.id}`}>Detalii <ArrowRight size={16} /></Link></article>)}</div></div></section>}
    <section className="business-cta"><div className="container"><div><p className="kicker">{value(content, "finalKicker")}</p><h2>{value(content, "finalTitle")}</h2><p>{value(content, "finalCopy")}</p></div><div><Link className="button button-cream" href={value(content, "finalCtaHref")}>{value(content, "finalCtaLabel")}</Link></div></div></section>
  </>;
}

function ImageCredit({ image }: { image: ReturnType<typeof resolveCmsImage> }) { const parts = [image.author ? `Foto: ${image.author}` : "", image.sourceUrl ? "Sursă" : "", image.license].filter(Boolean); return parts.length ? <p className="image-credit">{parts.join(" · ")}{image.sourceUrl && <> · <a href={image.sourceUrl} target="_blank" rel="noreferrer">detalii</a></>}</p> : null; }
function SectionHead({ eyebrow, title, href, link, light = false }: { eyebrow: string; title: string; href: string; link: string; light?: boolean }) { return <div className={`section-head ${light ? "light" : ""}`}><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div><Link className="text-link" href={href}>{link} <ArrowRight size={17} /></Link></div>; }
