"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { Archive, Check, Copy, Eye, RotateCcw, Save, Send, Trash2, Upload, X } from "lucide-react";
import { StructuredDraftPreview } from "./PublicPages";
import { richTextToPlainText } from "../rich-text";
import { RichTextEditor } from "./RichText";

export const statusLabels: Record<string, string> = {
  draft: "Ciornă", pending_review: "În verificare", needs_changes: "Necesită modificări", approved: "Aprobat",
  scheduled: "Programat", published: "Publicat", rejected: "Respins", expired: "Expirat", archived: "Arhivat", soft_deleted: "Șters",
};

export const typeLabels: Record<string, string> = {
  business: "Afacere", community_post: "Postare comunitară", local_story: "Poveste locală", article: "Articol editorial",
  business_update: "Actualizare de afacere", event: "Eveniment", offer: "Ofertă", job: "Job", restaurant: "Restaurant",
  daily_menu: "Meniul zilei", place: "Loc de descoperit",
};

type EditorMedia = { id:number;url:string;altText:string;approvalStatus:string;mediaStatus:string;width:number|null;height:number|null };
type ContentItem = { id: number; type: string; title: string; slug?:string; excerpt: unknown; status: string; moderation_state: string; updated_at: string; version: number; business_id: number | null; category_id?:number|null; seo_title?:string|null; seo_description?:string|null; body?:unknown;locality?:string;sourceUrl?:string;details?:Record<string,unknown>;publicVersionPreserved?:boolean;primaryMediaId?:number|null;primaryMediaAltText?:string;primaryMediaState?:"legacy"|"selected"|"none";media?:EditorMedia|null;editor_media_id?:number|null;editor_media_alt?:string|null };
type BusinessOption = { id: number; name: string };
type MediaOption = { id: number; title: string | null; original_filename: string | null; approval_status: string; media_status: string };

export function ContentList({ items, admin = false }: { items: ContentItem[]; admin?: boolean }) {
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("");
  const [type, setType] = useState("");
  const [sort, setSort] = useState("updated");
  const [page,setPage]=useState(1);const pageSize=20;
  const filtered = useMemo(() => items.filter(item => (!status || item.status === status) && (!type || item.type === type) && item.title.toLocaleLowerCase("ro-RO").includes(query.toLocaleLowerCase("ro-RO"))).sort((a,b)=>sort==="title"?a.title.localeCompare(b.title,"ro-RO"):String(b.updated_at).localeCompare(String(a.updated_at))), [items, query, status, type,sort]);
  const pages=Math.max(1,Math.ceil(filtered.length/pageSize));const visible=filtered.slice((Math.min(page,pages)-1)*pageSize,Math.min(page,pages)*pageSize);
  return <div>
    <div className="management-toolbar"><input aria-label="Caută în conținut" placeholder="Caută după titlu" value={query} onChange={event => {setQuery(event.target.value);setPage(1)}} /><select aria-label="Filtrează după tip" value={type} onChange={event => {setType(event.target.value);setPage(1)}}><option value="">Toate tipurile</option>{Object.entries(typeLabels).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select><select aria-label="Filtrează după stare" value={status} onChange={event => {setStatus(event.target.value);setPage(1)}}><option value="">Toate stările</option>{Object.entries(statusLabels).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select><select aria-label="Sortează conținutul" value={sort} onChange={event=>{setSort(event.target.value);setPage(1)}}><option value="updated">Actualizate recent</option><option value="title">Titlu A–Z</option></select><Link className="button" href={admin?"/admin/continut/nou":"/cont/continut/nou"}>Creează</Link></div>
    <p aria-live="polite">{filtered.length} materiale · pagina {Math.min(page,pages)} din {pages}</p><div className="management-list">{visible.map(item => <article className="management-row" key={item.id}>{item.editor_media_id&&<img className="management-thumbnail" src={`/api/media/${item.editor_media_id}?width=320`} alt={item.editor_media_alt||item.title} width="160" height="107" loading="lazy"/>}<div><span className={`status-pill status-${item.status}`}>{statusLabels[item.status] || item.status}</span><small>{typeLabels[item.type] || item.type}</small><h3>{item.title || "Ciornă fără titlu"}</h3><p>{plain(item.excerpt) || "Fără rezumat"}</p><time>Salvat {formatDate(item.updated_at)}</time></div><div className="management-actions"><Link href={admin?`/admin/continut/${item.type}/${item.id}`:`/cont/continut/${item.id}`}><Eye /> Deschide</Link>{!admin&&<><ContentAction id={item.id} action="duplicate" label="Duplică" icon="copy" />{item.status === "published" && <ContentAction id={item.id} action="archive" label="Arhivează" icon="archive" />}{item.status === "archived" && <ContentAction id={item.id} action="restore" label="Restaurează" icon="restore" />}</>}</div></article>)}</div>{pages>1&&<nav className="pagination" aria-label="Paginare conținut"><button disabled={page<=1} onClick={()=>setPage(value=>Math.max(1,value-1))}>Pagina anterioară</button><button disabled={page>=pages} onClick={()=>setPage(value=>Math.min(pages,value+1))}>Pagina următoare</button></nav>}
    {filtered.length === 0 && <div className="management-empty"><h3>Nu există rezultate</h3><p>Schimbă filtrele sau creează o ciornă nouă.</p></div>}
  </div>;
}

export function ContentEditor({ initial, businesses, admin = false }: { initial?: ContentItem; businesses: BusinessOption[]; admin?: boolean }) {
  const [type, setType] = useState(initial?.type || "community_post");
  const [state, setState] = useState<"idle"|"saving"|"saved"|"error">("idle");
  const [message, setMessage] = useState("");
  const [errors, setErrors] = useState<Record<string,string>>({});
  const [saved, setSaved] = useState(initial);
  const [preview, setPreview] = useState(false);
  const [previewItem,setPreviewItem]=useState<ContentItem|undefined>(initial);
  const [mediaOptions, setMediaOptions] = useState<MediaOption[]>([]);
  const [selectedMediaId, setSelectedMediaId] = useState("");
  const [currentMedia,setCurrentMedia]=useState<EditorMedia|null>(initial?.media||null);
  const [selectedFile,setSelectedFile]=useState<File|null>(null);
  const [altText,setAltText]=useState(initial?.media?.altText||initial?.primaryMediaAltText||"");
  const localPreviewUrl=useMemo(()=>selectedFile?URL.createObjectURL(selectedFile):"",[selectedFile]);
  const formRef=useRef<HTMLFormElement>(null);
  const fileRef=useRef<HTMLInputElement>(null);const uploadIdRef=useRef("");const inFlightRef=useRef(false);const submitInFlightRef=useRef(false);
  useEffect(() => { if (admin) void fetch("/api/media?scope=all").then(response => response.json()).then((data: { items?: MediaOption[] }) => setMediaOptions((data.items || []).filter(item => item.media_status === "active"))); }, [admin]);
  useEffect(()=>()=>{if(localPreviewUrl)URL.revokeObjectURL(localPreviewUrl)},[localPreviewUrl]);
  function readPayload(element:HTMLFormElement){
    const form = new FormData(element);
    const media = form.get("media");
    const details: Record<string, unknown> = {};
    for (const [key, value] of form.entries()) if (key.startsWith("detail.")) details[key.slice(7)] = value;
    for (const key of ["familyFriendly","delivery","pickup","transport"]) details[key] = form.has(`detail.${key}`);
    const payload = { type, title: form.get("title"), slug: form.get("slug"), excerpt: form.get("excerpt"), body: form.get("body"), locality: form.get("locality"), categoryId: form.get("categoryId") ? Number(form.get("categoryId")) : null, businessId: form.get("businessId") ? Number(form.get("businessId")) : null, sourceUrl: form.get("sourceUrl"), seoTitle: form.get("seoTitle"), seoDescription: form.get("seoDescription"), version: saved?.version, primaryMediaId:currentMedia?.id??null,primaryMediaAltText:altText,primaryMediaState:(currentMedia||selectedFile)?"selected" as const:"none" as const, details };
    return{form,media,details,payload};
  }
  async function saveDraft(element:HTMLFormElement) {
    if(inFlightRef.current)return null;inFlightRef.current=true;setState("saving");setMessage("");setErrors({});
    try{
      const {form,details,payload}=readPayload(element);let selected=currentMedia;
      if(admin&&selectedMediaId&&!selectedFile){const option=mediaOptions.find(item=>item.id===Number(selectedMediaId));if(option)selected={id:option.id,url:`/api/media/${option.id}`,altText,approvalStatus:option.approval_status,mediaStatus:option.media_status,width:null,height:null}}
      if(selectedFile){if(!altText.trim()){setState("error");setMessage("Adaugă un text alternativ semnificativ pentru imagine.");return null}const upload=new FormData();upload.set("file",selectedFile);upload.set("altText",altText);upload.set("title",String(form.get("title")||""));upload.set("uploadId",uploadIdRef.current||(uploadIdRef.current=crypto.randomUUID()));if(payload.businessId)upload.set("businessId",String(payload.businessId));const mediaResponse=await fetch("/api/media",{method:"POST",body:upload});const mediaData=await mediaResponse.json() as{error?:string;media?:EditorMedia};if(!mediaResponse.ok||!mediaData.media){setState("error");setMessage(mediaData.error||"Imaginea nu a putut fi încărcată. Încearcă din nou.");return null}selected=mediaData.media;setCurrentMedia(selected);setSelectedFile(null);if(fileRef.current)fileRef.current.value=""}
      const finalPayload={...payload,primaryMediaId:selected?.id??null,primaryMediaAltText:selected?altText:"",primaryMediaState:selected?"selected":"none"};
      const response=await fetch(saved?`/api/account/content/${saved.id}`:"/api/account/content",{method:saved?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(finalPayload)});const data=await response.json() as ContentItem&{error?:string};
      if(!response.ok){setState("error");setMessage(data.error||"Ciorna nu a putut fi salvată.");return null}
      const next={...(saved||{type,status:"draft",moderation_state:"draft",updated_at:new Date().toISOString(),business_id:payload.businessId}),...data,title:String(form.get("title")||""),excerpt:form.get("excerpt"),body:form.get("body"),locality:String(form.get("locality")||""),sourceUrl:String(form.get("sourceUrl")||""),details,media:data.media??selected} as ContentItem;
      setSaved(next);setPreviewItem(next);setCurrentMedia(next.media||null);setState("saved");setMessage("Ciorna a fost salvată.");uploadIdRef.current="";
      if(!initial&&data.id)history.replaceState(null,"",admin?`/admin/continut/${type}/${data.id}`:`/cont/continut/${data.id}`);return next;
    }finally{inFlightRef.current=false}
  }
  async function submitForReview(){
    if(submitInFlightRef.current)return;submitInFlightRef.current=true;
    try{const element=formRef.current;if(!element)return;
      if(type==="business"&&!validateBusinessForm(element))return;
      const next=await saveDraft(element);if(!next)return;
      setState("saving");setMessage("");
      const response=await fetch(`/api/account/content/${next.id}/actions`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"submit",expectedVersion:next.version})});
      const data=await response.json() as{error?:string};
      if(!response.ok){setState("error");setMessage(data.error||"Materialul nu a putut fi trimis.");return}
      location.reload();
    }finally{submitInFlightRef.current=false}
  }
  function validateBusinessForm(element:HTMLFormElement){
    const {form}=readPayload(element);const next:Record<string,string>={};
    if(!String(form.get("title")||"").trim())next.title="Introdu un titlu.";
    if(!String(form.get("locality")||"").trim())next.locality="Selectează localitatea.";
    try{if(!richTextToPlainText(form.get("excerpt")||""))next.excerpt="Adaugă un rezumat."}catch{next.excerpt="Adaugă un rezumat."}
    if(!String(form.get("detail.address")||"").trim())next.address="Introdu adresa.";
    const phone=String(form.get("detail.phone")||"").trim();const digits=phone.replace(/\D/g,"");if(!/^[+\d][\d\s().\-/]{6,24}$/.test(phone)||digits.length<9||digits.length>15)next.phone="Introdu un număr de telefon valid.";
    setErrors(next);if(!Object.keys(next).length)return true;
    setState("error");setMessage("Verifică informațiile obligatorii pentru trimitere.");
    const first=Object.keys(next)[0];requestAnimationFrame(()=>{const target=first==="excerpt"?element.querySelector<HTMLElement>(".rte-field .rte-editor"):element.querySelector<HTMLElement>(`[data-publication-field="${first}"]`);target?.focus()});return false;
  }
  function showPreview(){const element=formRef.current;if(!element||state==="saving")return;const{form,details,payload}=readPayload(element);const title=String(form.get("title")||"");let excerpt="";try{excerpt=richTextToPlainText(form.get("excerpt")||"")}catch{/* handled below */}if(!title.trim()&&!excerpt){setState("error");setMessage("Adaugă un titlu sau un rezumat pentru o previzualizare relevantă.");return}const media=localPreviewUrl?{id:0,url:localPreviewUrl,altText,approvalStatus:"local",mediaStatus:"active",width:null,height:null}:currentMedia;setPreviewItem({...(saved||{}),id:saved?.id||0,type,title,excerpt:form.get("excerpt"),body:form.get("body"),locality:String(payload.locality||""),details,media} as ContentItem);setPreview(value=>!value);setMessage("")}
  const locked = saved?.status === "pending_review" || saved?.moderation_state === "pending_review" || saved?.status === "soft_deleted";
  return <>
    <form ref={formRef} className="content-editor" onSubmit={event=>{event.preventDefault();void saveDraft(event.currentTarget)}} noValidate={type==="business"}>
      <div className="editor-status"><span className={`status-pill status-${saved?.status || "draft"}`}>{statusLabels[saved?.status || "draft"]}</span><span>{saved ? `Versiunea ${saved.version}` : "Ciornă nouă"}</span>{message && <strong className={state === "error" ? "error-message" : "success-message"} role="status">{message}</strong>}</div>
      {(saved?.status === "pending_review"||saved?.moderation_state==="pending_review") && <div className="moderation-note"><strong>Materialul este în verificare.</strong><span>Retrage trimiterea înainte de a-l modifica. Versiunea publicată, dacă există, rămâne neschimbată.</span></div>}
      {saved?.status === "soft_deleted" && <div className="moderation-note"><strong>Materialul este șters recuperabil.</strong><span>Un administrator trebuie să îl recupereze înainte de editare.</span></div>}
      <fieldset disabled={locked || state === "saving"}><legend>Tipul materialului</legend><select name="type" value={type} onChange={event => setType(event.target.value)} disabled={Boolean(saved)}>{Object.entries(typeLabels).filter(([value]) => admin || value !== "article").map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></fieldset>
      {businesses.length > 0 && <label>Afacerea asociată<select name="businessId" defaultValue={initial?.business_id || ""}><option value="">Fără afacere</option>{businesses.map(business => <option value={business.id} key={business.id}>{business.name}</option>)}</select></label>}
      <label>Titlu<input name="title" required={type!=="business"} aria-invalid={Boolean(errors.title)} aria-describedby={errors.title?"title-error":undefined} data-publication-field="title" maxLength={240} defaultValue={initial?.title ?? ""} disabled={locked} />{errors.title&&<span id="title-error" className="error-message">{errors.title}</span>}</label>
      <div className="editor-grid"><label>Slug unic<input name="slug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" maxLength={120} defaultValue={initial?.slug??""} placeholder="generat automat din titlu" disabled={locked}/><small>Opțional. Dacă rămâne gol, este generat în siguranță din titlu.</small></label><label>ID categorie<input name="categoryId" type="number" min="1" defaultValue={initial?.category_id??(Number(initial?.details?.category_id)||"")} disabled={locked}/><small>Opțional pentru afaceri.</small></label><label>Localitate<input name="locality" required={type!=="business"} aria-invalid={Boolean(errors.locality)} aria-describedby={errors.locality?"locality-error":undefined} data-publication-field="locality" maxLength={120} defaultValue={initial?.locality??"Blaj"} disabled={locked} />{errors.locality&&<span id="locality-error" className="error-message">{errors.locality}</span>}</label><label>Sursă oficială sau de verificare<input name="sourceUrl" type="url" maxLength={800} defaultValue={initial?.sourceUrl??""} disabled={locked} /></label></div>
      <RichTextEditor name="excerpt" label="Rezumat" description="Textul public principal. Poți salva ciorna incompletă; pentru o afacere, rezumatul este obligatoriu numai la trimitere sau publicare." defaultValue={initial?.excerpt} required={type!=="business"} disabled={locked} maxCharacters={6000} error={errors.excerpt}/>
      {(["community_post","local_story","article","business_update"].includes(type)) && (
        <RichTextEditor name="body" label="Conținut" description="Folosește titluri de nivel 2 sau 3, liste, citate și legături sigure. Titlul paginii rămâne singurul H1." defaultValue={initial?.body} required disabled={locked} maxCharacters={30000}/>
      )}
      <TypeFields type={type} locked={locked} details={initial?.details||{}} errors={errors} />
      <fieldset className="editor-grid"><legend>SEO</legend><label>Titlu SEO<input name="seoTitle" maxLength={180} defaultValue={initial?.seo_title||String(initial?.details?.seo_title||"")} disabled={locked}/></label><label>Descriere SEO<textarea name="seoDescription" maxLength={300} rows={3} defaultValue={initial?.seo_description||String(initial?.details?.seo_description||"")} disabled={locked}/></label></fieldset>
      {admin&&<label>Imagine existentă din bibliotecă<select value={selectedMediaId} onChange={event=>setSelectedMediaId(event.target.value)} disabled={locked||state==="saving"}><option value="">Nu atașa o imagine existentă</option>{mediaOptions.map(item=><option value={item.id} key={item.id}>{item.title||item.original_filename||`Imagine #${item.id}`} · {item.approval_status}</option>)}</select></label>}
      <fieldset className="media-upload" disabled={locked||state==="saving"}><legend>Imagine principală</legend>{(localPreviewUrl||currentMedia)&&<div className="editor-media-preview"><img src={localPreviewUrl||currentMedia?.url} alt={altText} width={currentMedia?.width||960} height={currentMedia?.height||640}/><button type="button" className="danger-action" onClick={()=>{setSelectedFile(null);setCurrentMedia(null);setAltText("");setSelectedMediaId("");uploadIdRef.current="";if(fileRef.current)fileRef.current.value=""}}><Trash2/>Elimină imaginea</button></div>}<label><Upload/><span>{localPreviewUrl||currentMedia?"Înlocuiește fotografia":"Încarcă o fotografie"}. Devine publică numai după aprobarea conținutului și a imaginii.</span><input ref={fileRef} name="media" type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>{const file=event.target.files?.[0]||null;setSelectedFile(file);uploadIdRef.current=file?crypto.randomUUID():""}} /></label><label>Text alternativ pentru imagine<input name="altText" maxLength={500} value={altText} onChange={event=>setAltText(event.target.value)}/></label><small>JPEG, PNG sau WebP, maximum 8 MB. Textul alternativ descrie informația transmisă de fotografie.</small></fieldset>
      <div className="editor-buttons"><button className="button" type="submit" disabled={locked || state === "saving"}><Save /> {state === "saving" ? "Se salvează…" : "Salvează ciorna"}</button><button className="button button-outline" type="button" onClick={showPreview} disabled={state==="saving"}><Eye /> Previzualizează</button>{saved&&(saved.status==="pending_review"||saved.moderation_state==="pending_review")?<ContentAction id={saved.id} action="withdraw" label="Retrage trimiterea" icon="x" expectedVersion={saved.version}/>:<button type="button" onClick={()=>void submitForReview()} disabled={state==="saving"}><Send/>Trimite spre verificare</button>}{saved && ["draft","needs_changes","rejected"].includes(saved.status) && <ContentAction id={saved.id} action="delete" label="Șterge ciorna" icon="trash" danger expectedVersion={saved.version}/>}</div>
    </form>
    {preview&&previewItem&&<StructuredDraftPreview item={{id:previewItem.id,type:previewItem.type||type,title:previewItem.title||"Titlul materialului",excerpt:previewItem.excerpt,body:previewItem.body,locality:previewItem.locality,details:previewItem.details,media:previewItem.media}}/>}
  </>;
}

function TypeFields({ type, locked,details,errors }: { type: string; locked: boolean;details:Record<string,unknown>;errors:Record<string,string> }) {
  const value=(camel:string,snake=camel)=>String(details[camel]??details[snake]??"");
  const raw=(camel:string,snake=camel)=>details[camel]??details[snake]??"";
  if (type === "event") return <div className="editor-grid"><label>Organizator<input name="detail.organizer" required defaultValue={value("organizer")} disabled={locked} /></label><label>Locul evenimentului<input name="detail.venue" required defaultValue={value("venue")} disabled={locked} /></label><label>Începe la<input name="detail.startsAt" type="datetime-local" required defaultValue={value("startsAt","starts_at").slice(0,16)} disabled={locked} /></label><label>Se încheie la<input name="detail.endsAt" type="datetime-local" defaultValue={value("endsAt","ends_at").slice(0,16)} disabled={locked} /></label><label>Adresă<input name="detail.address" defaultValue={value("address")} disabled={locked} /></label><label>Informații bilete<input name="detail.ticketInfo" defaultValue={value("ticketInfo","ticket_info")} disabled={locked} /></label><label>Accesibilitate<textarea name="detail.accessibility" rows={3} defaultValue={value("accessibility")} disabled={locked}/></label><label>Imagine externă<input name="detail.imageUrl" type="url" defaultValue={value("imageUrl","image_url")} disabled={locked}/></label><label className="consent"><input name="detail.familyFriendly" type="checkbox" defaultChecked={Boolean(details.family_friendly||details.familyFriendly)} disabled={locked}/> Potrivit pentru familii</label></div>;
  if (type === "offer") return <div className="editor-grid"><label>Începe la<input name="detail.startsAt" type="date" required defaultValue={value("startsAt","starts_at").slice(0,10)} disabled={locked} /></label><label>Se încheie la<input name="detail.endsAt" type="date" required defaultValue={value("endsAt","ends_at").slice(0,10)} disabled={locked} /></label><label>Preț promoțional<input name="detail.price" type="number" min="0" step="0.01" defaultValue={value("price")} disabled={locked} /></label><label>Preț inițial<input name="detail.oldPrice" type="number" min="0" step="0.01" defaultValue={value("oldPrice","old_price")} disabled={locked} /></label><label>Disponibilitate<input name="detail.availability" defaultValue={value("availability")||"active"} disabled={locked}/></label><label>Imagine externă<input name="detail.imageUrl" type="url" defaultValue={value("imageUrl","image_url")} disabled={locked}/></label><RichTextEditor name="detail.terms" label="Condiții" description="Condițiile publice ale ofertei, în format semantic." defaultValue={raw("terms")} disabled={locked} maxCharacters={3000}/></div>;
  if (type === "job") return <div className="editor-grid"><label>Companie<input name="detail.company" required defaultValue={value("company")} disabled={locked} /></label><label>Tip contract<input name="detail.contractType" defaultValue={value("contractType","contract_type")} disabled={locked} /></label><label>Program<input name="detail.schedule" defaultValue={value("schedule")} disabled={locked} /></label><label>Schimb<input name="detail.shift" defaultValue={value("shift")} disabled={locked}/></label><label>Mod de lucru<input name="detail.workArrangement" defaultValue={value("workArrangement","work_arrangement")} disabled={locked} /></label><label>Salariu minim<input name="detail.salaryMin" type="number" min="0" defaultValue={value("salaryMin","salary_min")} disabled={locked} /></label><label>Salariu maxim<input name="detail.salaryMax" type="number" min="0" defaultValue={value("salaryMax","salary_max")} disabled={locked} /></label><RichTextEditor name="detail.responsibilities" label="Responsabilități" description="Descrie responsabilitățile postului." defaultValue={raw("responsibilities")} disabled={locked} maxCharacters={8000}/><RichTextEditor name="detail.requirements" label="Cerințe" description="Descrie cerințele postului." defaultValue={raw("requirements")} disabled={locked} maxCharacters={8000}/><RichTextEditor name="detail.benefits" label="Beneficii" description="Descrie beneficiile oferite." defaultValue={raw("benefits")} disabled={locked} maxCharacters={8000}/><label>Termen limită<input name="detail.deadline" type="date" defaultValue={value("deadline").slice(0,10)} disabled={locked} /></label><label>Link de aplicare<input name="detail.applyUrl" type="url" defaultValue={value("applyUrl","apply_url")} disabled={locked} /></label><label className="editor-span">Modalitate de aplicare<textarea name="detail.applicationMethod" rows={3} defaultValue={value("applicationMethod","application_method")} disabled={locked}/></label><label className="consent"><input name="detail.transport" type="checkbox" defaultChecked={Boolean(details.transport_provided||details.transport)} disabled={locked}/> Transport oferit</label></div>;
  if (type === "business") return <div className="editor-grid"><label>Adresă<input name="detail.address" data-publication-field="address" aria-invalid={Boolean(errors.address)} aria-describedby={errors.address?"address-error":undefined} defaultValue={value("address")} disabled={locked} />{errors.address&&<span id="address-error" className="error-message">{errors.address}</span>}</label><label>Telefon<input name="detail.phone" type="tel" data-publication-field="phone" aria-invalid={Boolean(errors.phone)} aria-describedby={errors.phone?"phone-error":undefined} defaultValue={value("phone")} disabled={locked} />{errors.phone&&<span id="phone-error" className="error-message">{errors.phone}</span>}</label><label>Website<input name="detail.website" type="url" defaultValue={value("website")} disabled={locked} /></label><label>E-mail public<input name="detail.contactEmail" type="email" defaultValue={value("contactEmail","contact_email")} disabled={locked}/></label><label>WhatsApp<input name="detail.whatsapp" defaultValue={value("whatsapp")} disabled={locked}/></label><label>Linkuri sociale<textarea name="detail.socialLinks" rows={3} defaultValue={value("socialLinks","social_links")} disabled={locked}/></label></div>;
  if (type === "restaurant") return <div className="editor-grid"><label>Specific<input name="detail.cuisine" defaultValue={value("cuisine")} disabled={locked} /></label><label>Opțiuni alimentare<textarea name="detail.dietaryOptions" rows={3} defaultValue={value("dietaryOptions","dietary_options")} disabled={locked}/></label><label>Imagine externă<input name="detail.imageUrl" type="url" defaultValue={value("imageUrl","image_url")} disabled={locked}/></label><label className="consent"><input name="detail.delivery" type="checkbox" defaultChecked={Boolean(details.delivery)} disabled={locked} /> Livrare</label><label className="consent"><input name="detail.pickup" type="checkbox" defaultChecked={Boolean(details.pickup)} disabled={locked} /> Ridicare</label></div>;
  if (type === "daily_menu") return <div className="editor-grid"><label>Data meniului<input name="detail.menuDate" type="date" required defaultValue={value("menuDate","menu_date").slice(0,10)} disabled={locked} /></label><label>Restaurant ID<input name="detail.restaurantId" type="number" required defaultValue={value("restaurantId","restaurant_id")} disabled={locked} /></label><label>Supă / ciorbă<input name="detail.soup" defaultValue={value("soup")} disabled={locked} /></label><label>Fel principal<input name="detail.mainDish" defaultValue={value("mainDish","main_dish")} disabled={locked} /></label><label>Garnitură<input name="detail.sideDish" defaultValue={value("sideDish","side_dish")} disabled={locked} /></label><label>Desert<input name="detail.dessert" defaultValue={value("dessert")} disabled={locked} /></label><label>Preț<input name="detail.price" type="number" min="0" step="0.01" defaultValue={value("price")} disabled={locked} /></label><label>Termen comenzi<input name="detail.orderDeadline" type="time" defaultValue={value("orderDeadline","order_deadline")} disabled={locked}/></label><label>Disponibilitate<select name="detail.availability" defaultValue={value("availability")||"active"} disabled={locked}><option value="active">Activ</option><option value="sold_out">Epuizat</option><option value="unavailable">Indisponibil</option></select></label></div>;
  if (type === "place") return <div className="editor-grid"><label>Adresă<input name="detail.address" defaultValue={value("address")} disabled={locked}/></label><label>Accesibilitate<textarea name="detail.accessibility" rows={3} defaultValue={value("accessibility")} disabled={locked}/></label><label>Imagine externă<input name="detail.imageUrl" type="url" defaultValue={value("imageUrl","image_url")} disabled={locked}/></label></div>;
  return null;
}

export function ContentAction({ id, action, label, icon, danger = false,expectedVersion }: { id: number; action: string; label: string; icon: string; danger?: boolean;expectedVersion?:number }) {
  const [busy, setBusy] = useState(false);
  const Icon = icon === "copy" ? Copy : icon === "archive" ? Archive : icon === "restore" ? RotateCcw : icon === "trash" ? Trash2 : icon === "x" ? X : Send;
  async function run() {
    if (["archive","withdraw","delete"].includes(action) && !window.confirm(`Confirmi acțiunea „${label}”?`)) return;
    setBusy(true);
    const response = await fetch(`/api/account/content/${id}/actions`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action,expectedVersion }) });
    const data = await response.json() as { error?: string };
    if (!response.ok) window.alert(data.error || "Acțiunea nu a putut fi finalizată."); else location.reload();
    setBusy(false);
  }
  return <button className={danger ? "danger-action" : ""} type="button" onClick={run} disabled={busy}><Icon /> {busy ? "Se procesează…" : label}</button>;
}

export function BusinessRegistrationForm() {
  const [message, setMessage] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const payload = Object.fromEntries(form); const response = await fetch("/api/account/businesses", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json() as { error?: string }; setMessage(response.ok ? "Afacerea a fost trimisă spre verificare." : data.error || "Cererea nu a putut fi trimisă."); if (response.ok) event.currentTarget.reset(); }
  return <form className="content-editor" onSubmit={submit}><div className="form-alert"><strong>Cinci informații sunt necesare pentru publicare.</strong><p>Poți completa opțional site-ul, e-mailul și o sursă de verificare.</p></div><label>Titlu *<input name="name" required /></label><div className="editor-grid"><label>Localitate *<input name="locality" required defaultValue="Blaj" /></label><label>Adresă *<input name="address" required /></label><label>Telefon *<input name="phone" required type="tel" /></label><label>Website<input name="website" type="url" /></label><label>E-mail public<input name="contactEmail" type="email" /></label><label>Dovadă sau sursă de verificare<input name="evidenceUrl" type="url" /></label></div><RichTextEditor name="description" label="Rezumat" description="Descrie pe scurt activitatea afacerii." required maxCharacters={6000}/><label className="consent"><input type="checkbox" required /> Confirm că informațiile sunt corecte și am dreptul să reprezint afacerea.</label><button className="button" type="submit">Trimite spre verificare</button>{message && <p role="status">{message}</p>}</form>;
}

export function ClaimBusinessForm({ businesses }: { businesses: BusinessOption[] }) {
  const [message, setMessage] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const response = await fetch("/api/account/claims", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) }); const data = await response.json() as { error?: string }; setMessage(response.ok ? "Revendicarea a fost trimisă spre verificare." : data.error || "Cererea nu a putut fi trimisă."); }
  return <form className="content-editor" onSubmit={submit}><label>Afacerea<select name="businessId" required><option value="">Selectează</option>{businesses.map(business => <option value={business.id} key={business.id}>{business.name}</option>)}</select></label><label>Explică relația cu afacerea<textarea name="explanation" required rows={6} /></label><label>Dovadă sau document public<input name="evidenceUrl" type="url" /></label><label>Date de contact pentru verificare<textarea name="contactInformation" required rows={3} /></label><button className="button" type="submit">Trimite revendicarea</button>{message && <p role="status">{message}</p>}</form>;
}

export function InvitationAction({ membershipId }: { membershipId: number }) {
  const [busy, setBusy] = useState(false);
  async function run(action: "accept_invitation"|"decline_invitation") { setBusy(true); await fetch("/api/account/claims", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, membershipId }) }); location.reload(); }
  return <div className="inline-actions"><button className="button button-small" disabled={busy} onClick={() => run("accept_invitation")}><Check /> Acceptă</button><button className="button button-outline" disabled={busy} onClick={() => run("decline_invitation")}><X /> Refuză</button></div>;
}

export function NotificationActions() { const [busy,setBusy] = useState(false); return <button className="button button-outline" disabled={busy} onClick={async () => { setBusy(true); await fetch("/api/account/notifications", { method:"POST", headers:{"content-type":"application/json"}, body:JSON.stringify({ action:"read_all" }) }); location.reload(); }}>Marchează toate ca citite</button>; }

const weekdayLabels=["Luni","Marți","Miercuri","Joi","Vineri","Sâmbătă","Duminică"];
export function BusinessHoursManager({businessId,items}:{businessId:number;items:Array<{weekday:number;opens_at:string|null;closes_at:string|null;closed:number}>}){
  const initial=weekdayLabels.map((_,weekday)=>{const row=items.find(item=>item.weekday===weekday);return{weekday,opensAt:row?.opens_at||"09:00",closesAt:row?.closes_at||"17:00",closed:Boolean(row?.closed)}});
  const[hours,setHours]=useState(initial);const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
  async function save(){setBusy(true);const response=await fetch(`/api/businesses/${businessId}/hours`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({hours})});const data=await response.json() as{error?:string};setMessage(response.ok?"Programul a fost salvat.":data.error||"Programul nu a putut fi salvat.");setBusy(false)}
  return <section className="account-panel hours-editor"><h2>Program săptămânal</h2>{hours.map((row,index)=><div className="hours-row" key={row.weekday}><strong>{weekdayLabels[index]}</strong><label><span>Deschide</span><input type="time" value={row.opensAt} disabled={row.closed} onChange={event=>setHours(current=>current.map(item=>item.weekday===row.weekday?{...item,opensAt:event.target.value}:item))}/></label><label><span>Închide</span><input type="time" value={row.closesAt} disabled={row.closed} onChange={event=>setHours(current=>current.map(item=>item.weekday===row.weekday?{...item,closesAt:event.target.value}:item))}/></label><label className="consent"><input type="checkbox" checked={row.closed} onChange={event=>setHours(current=>current.map(item=>item.weekday===row.weekday?{...item,closed:event.target.checked}:item))}/> Închis</label></div>)}<button className="button" onClick={save} disabled={busy}>{busy?"Se salvează…":"Salvează programul"}</button>{message&&<p role="status">{message}</p>}</section>
}

export function BusinessMediaManager({businessId,contentId,items}:{businessId:number;contentId?:number;items:Array<{id:number;title:string|null;original_filename:string|null;alt_text:string|null;approval_status:string;media_status:string}>}){
  const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
  async function upload(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);form.set("businessId",String(businessId));if(contentId)form.set("contentId",String(contentId));const response=await fetch("/api/media",{method:"POST",body:form});const data=await response.json() as{error?:string};if(response.ok)location.reload();else setMessage(data.error||"Imaginea nu a putut fi încărcată.");setBusy(false)}
  async function archive(id:number){if(!confirm("Arhivezi această imagine?"))return;const response=await fetch(`/api/media/${id}`,{method:"DELETE"});if(response.ok)location.reload();else{const data=await response.json() as{error?:string};setMessage(data.error||"Imaginea nu a putut fi arhivată.")}}
  return <><form className="content-editor media-manager" onSubmit={upload}><h2>Adaugă fotografie</h2><label>Imagine<input name="file" type="file" accept="image/jpeg,image/png,image/webp" required/></label><label>Alt text<input name="altText" required maxLength={500}/></label><div className="editor-grid"><label>Titlu<input name="title" maxLength={240}/></label><label>Fotograf<input name="photographer" maxLength={240}/></label><label>Sursă<input name="sourceUrl" type="url" maxLength={800}/></label><label>Licență<input name="license" maxLength={120}/></label></div><button className="button" disabled={busy}>{busy?"Se încarcă…":"Încarcă fotografia"}</button>{message&&<p role="alert">{message}</p>}</form><div className="media-grid">{items.map(item=><article className="media-card" key={item.id}><img src={`/api/media/${item.id}`} alt={item.alt_text||""} width="640" height="480" loading="lazy"/><span className="status-pill">{item.approval_status}</span><h3>{item.title||item.original_filename||`Imagine #${item.id}`}</h3><button className="danger-action" onClick={()=>archive(item.id)}>Arhivează</button></article>)}</div></>
}

export function TeamManager({ businessId, items }: { businessId: number; items: Array<{ id:number; display_name?:string; email?:string; invite_email?:string; membership_role:string; membership_status:string }> }) {
  const [message,setMessage] = useState("");
  async function invite(event:React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form=new FormData(event.currentTarget); const response=await fetch(`/api/businesses/${businessId}/team`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(form))}); const data=await response.json() as {error?:string}; setMessage(response.ok?"Invitația a fost creată.":data.error||"Invitația nu a putut fi creată."); if(response.ok) location.reload(); }
  return <><form className="team-invite" onSubmit={invite}><label>E-mail manager<input name="email" type="email" required /></label><button className="button" type="submit">Invită manager</button></form>{message&&<p role="status">{message}</p>}<div className="management-list">{items.map(item=><article className="management-row" key={item.id}><div><span className={`status-pill status-${item.membership_status}`}>{item.membership_status === "active" ? "Activ" : "Invitat"}</span><h3>{item.display_name||item.email||item.invite_email}</h3><p>{item.membership_role === "owner" ? "Proprietar" : "Manager"}</p></div>{item.membership_role !== "owner"&&<button className="danger-action" onClick={async()=>{if(confirm("Retragi accesul acestui manager?")){await fetch(`/api/businesses/${businessId}/team?membershipId=${item.id}`,{method:"DELETE"});location.reload();}}}><Trash2 /> Retrage accesul</button>}</article>)}</div></>;
}

function formatDate(value:string){ try { return new Intl.DateTimeFormat("ro-RO",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)); } catch { return value; } }
function plain(value:unknown){try{return richTextToPlainText(value)}catch{return String(value??"")}}
