"use client";

import Link from "next/link";
import { ArrowLeft, ArrowRight, CalendarDays, Check, ChevronRight, ExternalLink, Filter, MapPin, Search, Send, ShieldCheck, Upload } from "lucide-react";
import { demoNotice, useful } from "../data";
import type { PublicCatalog, PublicViewer } from "../public-types";
import { useMemo, useState } from "react";

const sectionMap: Record<string, { eyebrow: string; title: string; intro: string }> = {
  "evenimente": { eyebrow: "Calendar local", title: "Evenimente în Blaj", intro: "Găsește activități pentru familie, cultură, sport și comunitate. Toate exemplele neverificate sunt marcate clar." },
  "afaceri-si-servicii": { eyebrow: "Director local", title: "Afaceri și servicii", intro: "Caută un profesionist sau un serviciu în Blaj și localitățile apropiate." },
  "oferte-locale": { eyebrow: "Economisește local", title: "Oferte în Blaj", intro: "Oferte cu perioadă și condiții clare. Conținutul plătit este întotdeauna etichetat." },
  "unde-mancam": { eyebrow: "Bun, aproape", title: "Unde mâncăm", intro: "Restaurante, cafenele, brutării și meniuri zilnice, cu data ultimei actualizări la vedere." },
  "locuri-de-munca": { eyebrow: "Oportunități", title: "Locuri de muncă în apropiere", intro: "Joburi locale explicate clar: program, condiții, salariu când este comunicat și modalitatea de aplicare." },
  "informatii-utile": { eyebrow: "De păstrat la îndemână", title: "Informații utile", intro: "Legături practice și surse oficiale. Pentru informații urgente sau dependente de timp, confirmă direct cu instituția responsabilă." },
  "povesti-locale": { eyebrow: "Vocea comunității", title: "Povești și actualizări locale", intro: "Postări comunitare, povești locale, articole și noutăți de la afaceri, toate verificate înainte de publicare." },
};

type GenericItem = { id?: string; contentId?:number;entityId?:number;title?: string; name?: string; company?: string; business?: string;author?:string;excerpt?:string;body?:string; category?: string; type?: string; image?: string; date?: string; startDate?: string; time?: string; locality?: string; place?: string; dish?: string; price?: string; source?: string; text?: string; description?: string; isDemo?:boolean;verified?:boolean;promoted?:boolean;updatedAt?:string };

export function ListingPage({ slug, catalog }: { slug: string; catalog: PublicCatalog }) {
  const { events,businesses,offers,restaurants,jobs,posts }=catalog;
  const copy = sectionMap[slug];
  const [query, setQuery] = useState("");
  const normalize = (s: string) => s.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
  const all = slug === "evenimente" ? events : slug === "afaceri-si-servicii" ? businesses : slug === "oferte-locale" ? offers : slug === "unde-mancam" ? restaurants : slug === "locuri-de-munca" ? jobs : slug === "povesti-locale" ? posts : useful;
  const filtered = useMemo(() => all.filter(item => normalize(JSON.stringify(item)).includes(normalize(query))), [all, query]);
  return <><PageHero eyebrow={copy.eyebrow} title={copy.title} intro={copy.intro} /><section className="container directory-layout"><aside className="filters"><div><Filter size={18} /><strong>Filtre</strong></div><label>Localitate<select><option>Toate localitățile</option><option>Blaj</option><option>Sâncel</option><option>Jidvei</option><option>Valea Lungă</option></select></label><label>Categorie<select><option>Toate categoriile</option><option>Comunitate</option><option>Servicii</option><option>Familie</option></select></label><label className="check"><input type="checkbox" /> Doar listări active</label><button className="button button-outline">Aplică filtrele</button></aside><div className="results"><div className="results-tools"><label><Search size={18} /><input value={query} onInput={e => setQuery(e.currentTarget.value)} placeholder="Caută în rezultate" aria-label="Caută în rezultate" /></label><span>{filtered.length} rezultate publice</span></div><div className={`generic-list ${slug}`}>{filtered.map((item, i) => <GenericResult slug={slug} item={item as GenericItem} index={i} key={(item as GenericItem).id || (item as GenericItem).title} />)}</div>{filtered.length === 0 && <div className="empty-state"><Search /><h3>Nu am găsit rezultate.</h3><p>Încearcă un termen fără diacritice sau caută într-o categorie apropiată.</p><button className="button button-outline" onClick={() => setQuery("")}>Șterge căutarea</button></div>}</div></section></>;
}

function GenericResult({ slug, item, index }: { slug: string; item: GenericItem; index: number }) {
  if (slug === "informatii-utile") return <article className="utility-card"><span>0{index + 1}</span><div><h2>{item.title}</h2><p>{item.text}</p><a href={item.source} target="_blank" rel="noreferrer">Sursă oficială <ExternalLink size={15} /></a><small>Ultima verificare: 8 august 2026</small></div></article>;
  const title = item.title || item.name;
  const subtitle = item.author || item.company || item.business || item.category || item.type;
  return <article className="result-card">{item.image && <img src={item.image} alt="" loading="lazy" />}<div className="result-main">{item.promoted&&<span className="promoted">Promovat</span>}{item.isDemo&&<span className="demo-badge">Exemplu demonstrativ</span>}{item.verified&&<span className="verified-badge">Afacere verificată</span>}<p className="eyebrow">{subtitle}</p><h2>{title}</h2>{item.date && <p><CalendarDays size={16} /> {item.date} · {item.time}</p>}{(item.locality || item.place) && <p><MapPin size={16} /> {item.locality || item.place}</p>}{item.dish && <p>{item.dish}</p>}{item.price && <strong className="result-price">{item.price}</strong>}<Link href={`/${slug}/${item.id}`}>Vezi detaliile <ArrowRight size={16} /></Link></div></article>;
}

export function DiscoverPage({catalog}:{catalog:PublicCatalog}) {
  const places=catalog.places;
  return <><section className="discover-hero"><img src="/images/catedrala-blaj.jpg" alt="Catedrala Sfânta Treime din Blaj" /><div><p className="kicker">Istorie · cultură · oameni</p><h1>Descoperă Blajul</h1><p>Un oraș al istoriei, culturii și oamenilor care îi dau viață în fiecare zi.</p></div><small>Foto: Țetcu Mircea Rareș · Wikimedia Commons · CC BY-SA 4.0</small></section><section className="container intro-editorial"><p className="lead">Blajul este un municipiu din județul Alba, așezat la întâlnirea Târnavelor. Identitatea sa culturală și istorică poate fi explorată prin locuri, arhive și surse verificate.</p><p>În această primă versiune, folosim doar prezentări scurte, bazate pe lista oficială de obiective locale și pe materiale cu licență deschisă. Informațiile despre program sau acces vor apărea doar după confirmare.</p><a className="source-link" href="https://municipiulblaj.ro/comunitate/obiective-locale" target="_blank" rel="noreferrer">Sursă: Municipiul Blaj <ExternalLink size={15} /></a></section><section className="section container"><div className="section-head"><div><p className="eyebrow">Locuri și repere</p><h2>Patru puncte de pornire</h2></div></div><div className="places-grid">{places.map(p => <article className="place-card" key={p.id}><img src={p.image} alt={p.title} loading="lazy" /><div><p className="eyebrow">{p.eyebrow}</p><h3>{p.title}</h3><p>{p.text}</p><Link href={`/descopera-blaj/${p.id}`}>Află mai mult <ArrowRight /></Link></div></article>)}</div></section><Gallery places={places} /><Timeline /><section className="contribute-band"><div className="container"><div><p className="kicker">Arhiva comunității</p><h2>Ai fotografii sau povești despre Blaj?</h2><p>Trimite o amintire, o corectură sau un material. Nimic nu este publicat înainte de verificarea administratorului.</p></div><Link className="button button-cream" href="/contribuie">Contribuie la arhivă <ArrowRight /></Link></div></section></>;
}

function Gallery({places}:{places:PublicCatalog["places"]}) { const [active, setActive] = useState<string | null>(null); return <section id="imagini" className="gallery-section"><div className="container"><div className="section-head light"><div><p className="eyebrow">Blaj în imagini</p><h2>Orașul, privit cu atenție</h2></div><div className="chips dark"><button className="active">Toate</button><button>Arhitectură</button><button>Istorie</button></div></div><div className="gallery-grid">{places.map((p, i) => <button key={p.id} className={i === 0 ? "wide" : ""} onClick={() => setActive(p.id)}><img src={p.image} alt={p.title} loading="lazy" /><span>{p.title}<small>Vezi fotografia și atribuirea</small></span></button>)}</div><div id="video" className="video-row"><article><span>Video extern</span><h3>Obiective turistice din Blaj</h3><p>Material demonstrativ încorporat doar după interacțiune, din sursa originală.</p><a href="https://www.youtube.com/watch?v=JPF94Ns2dyU" target="_blank" rel="noreferrer">Deschide pe YouTube <ExternalLink /></a></article><article><span>Arhivă video</span><h3>Povești din comunitate</h3><p>Loc rezervat materialelor verificate de la instituții și contribuitori locali.</p><Link href="/contribuie">Propune un video <ArrowRight /></Link></article></div></div>{active && <div className="lightbox" role="dialog" aria-modal="true" aria-label="Fotografie mărită"><button className="lightbox-backdrop" aria-label="Închide fotografia" onClick={() => setActive(null)} /><button className="lightbox-close" aria-label="Închide" onClick={() => setActive(null)}>×</button>{places.filter(p => p.id === active).map(p => <figure key={p.id}><img src={p.image} alt={p.title} /><figcaption><strong>{p.title}</strong><span>{p.id === "adunarea-1848" ? "Autor necunoscut · Domeniul public" : "Țetcu Mircea Rareș · Wikimedia Commons · CC BY-SA 4.0"}</span></figcaption></figure>)}</div>}</section>; }

function Timeline() { return <section className="section container"><div className="section-head"><div><p className="eyebrow">Poveștile Blajului</p><h2>O cronologie care va crește responsabil</h2></div></div><ol className="timeline"><li><time>1848</time><div><h3>Adunarea de la Blaj</h3><p>Moment prezentat printr-o imagine istorică aflată în domeniul public. Detaliile editoriale vor fi completate numai cu surse academice și instituționale.</p><a href="https://commons.wikimedia.org/wiki/File:Blaj1848.jpg" target="_blank" rel="noreferrer">Vezi sursa</a></div></li><li><time>Astăzi</time><div><h3>O comunitate vie</h3><p>Blaj Azi adună informația locală într-un ghid practic, cu sursa și data verificării la vedere.</p></div></li></ol></section>; }

export function DetailPage({ section, id, catalog, viewer }: { section: string; id: string;catalog:PublicCatalog;viewer:PublicViewer }) {
  const {events,businesses,offers,restaurants,jobs,places,posts}=catalog;
  const pools: Record<string, GenericItem[]> = { "evenimente": events, "afaceri-si-servicii": businesses, "oferte-locale": offers, "unde-mancam": restaurants, "locuri-de-munca": jobs, "descopera-blaj": places,"povesti-locale":posts };
  const item = pools[section]?.find(x => x.id === id);
  if (!item) return <PageHero eyebrow="Informație indisponibilă" title="Această pagină nu este disponibilă" intro="Listarea poate fi expirată, arhivată sau încă în curs de verificare." />;
  const title = item.title || item.name;
  const schemaTypes: Record<string, string> = { "evenimente": "Event", "afaceri-si-servicii": "LocalBusiness", "oferte-locale": "Offer", "unde-mancam": "Restaurant", "locuri-de-munca": "JobPosting", "descopera-blaj": "Place","povesti-locale":"Article" };
  const jsonLd = { "@context": "https://schema.org", "@type": schemaTypes[section], name: title, description: item.text || item.excerpt || item.dish || demoNotice, address: { "@type": "PostalAddress", addressLocality: item.locality || "Blaj", addressRegion: "Alba", addressCountry: "RO" }, ...(section === "evenimente" ? { startDate: item.startDate, eventStatus: "https://schema.org/EventScheduled" } : {}), ...(section === "locuri-de-munca" ? { title, hiringOrganization: { "@type": "Organization", name: item.company }, employmentType: item.type } : {}) };
  return <>{["descopera-blaj","povesti-locale"].includes(section) && <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c") }} />}<section className="detail-hero">{item.image && <img src={item.image} alt={title} />}<div className="container"><Link href={`/${section}`} className="back-link"><ArrowLeft /> Înapoi la listă</Link>{item.isDemo&&<span className="demo-badge">Exemplu demonstrativ</span>}{item.verified&&<span className="verified-badge">Afacere verificată</span>}{item.promoted&&<span className="promoted">Promovat</span>}<h1>{title}</h1><p>{item.text || item.excerpt || item.description || item.dish || item.company || item.business || item.category}</p></div></section><section className="container detail-layout"><article><h2>{section==="povesti-locale"?"Povestea":"Informații pe scurt"}</h2><p>{item.body || item.text || item.excerpt || item.description || (item.isDemo?demoNotice:"")}</p><dl><div><dt>Localitate</dt><dd>{item.locality || "Blaj"}</dd></div><div><dt>Stare</dt><dd>Publicat</dd></div><div><dt>Actualizat</dt><dd>{formatPublicDate(item.updatedAt)}</dd></div>{item.author&&<div><dt>Autor</dt><dd>{item.author}</dd></div>}</dl>{item.source && <a className="button button-outline" href={item.source} target="_blank" rel="noreferrer">Vezi sursa oficială <ExternalLink /></a>}</article><aside><h3>Acțiuni rapide</h3>{section==="afaceri-si-servicii"&&<Link href={viewer.signedIn?`/cont/revendica-afacere?business=${item.entityId||""}`:"/signin-with-chatgpt?return_to=%2Fcont%2Frevendica-afacere"}>Reprezinți această afacere? Revendică profilul.</Link>}{viewer.canEdit&&item.contentId&&<Link href={`/cont/continut/${item.contentId}`}>Editează</Link>}{viewer.canEdit&&section==="afaceri-si-servicii"&&item.entityId&&<Link href={`/cont/afaceri/${item.entityId}`}>Administrează</Link>}{viewer.canAdmin&&item.contentId&&<Link href={`/admin/continut/${item.type||section}/${item.contentId}`}>Editează în administrare</Link>}<a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(title + " Blaj")}`} target="_blank" rel="noreferrer"><MapPin /> Vezi traseul</a><button><Send /> Distribuie</button><Link href="/contact"><ShieldCheck /> Raportează o informație</Link></aside></section></>;
}

export function SubmissionPage({ kind, account }: { kind: string;account?:{displayName:string;email:string}|null }) {
  const map: Record<string, [string, string]> = { business: ["Adaugă o afacere", "Creează gratuit o prezență locală. Vom verifica datele înainte de publicare."], event: ["Adaugă un eveniment", "Trimite un eveniment local pentru moderare."], offer: ["Publică o ofertă", "Prezintă clar perioada, prețul și condițiile ofertei."], job: ["Publică un loc de muncă", "Ajută oamenii din zonă să găsească oportunități clare și actuale."], contribution: ["Contribuie la arhiva Blajului", "Trimite o fotografie, o poveste, o corectură sau un link video."], contact: ["Scrie-ne", "Pentru întrebări, corecturi și propuneri de parteneriat."], promotion: ["Promovează în Blaj", "Alege vizibilitate locală transparentă. Prețurile vor fi configurate înainte de lansare."] };
  const [title, intro] = map[kind];
  return <><PageHero eyebrow="Trimite spre verificare" title={title} intro={intro} />{account&&<div className="container signed-form-note"><strong>Ești conectat ca {account.displayName}.</strong><span>Trimiterea va fi asociată contului tău.</span><Link href="/cont/continut/nou">Creează o ciornă editabilă</Link></div>}<SubmissionForm kind={kind} account={account} /></>;
}

function SubmissionForm({ kind,account }: { kind: string;account?:{displayName:string;email:string}|null }) {
  const [state, setState] = useState<"idle" | "sending" | "done" | "error">("idle");
  async function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); setState("sending"); const res = await fetch("/api/submissions", { method: "POST", body: new FormData(e.currentTarget) }); setState(res.ok ? "done" : "error"); }
  if (state === "done") return <section className="container success-page"><Check /><p className="eyebrow">Trimitere înregistrată</p><h2>Mulțumim. Informația a intrat în lista de moderare.</h2><p>Nu va fi publicată automat. Administratorul o va verifica și poate solicita completări.</p><Link className="button" href="/">Înapoi la pagina principală</Link></section>;
  return <section className="container form-layout"><form className="submission-form" onSubmit={submit} encType="multipart/form-data"><input type="hidden" name="type" value={kind} /><input className="honeypot" name="website" tabIndex={-1} autoComplete="off" aria-hidden="true" /><label>Nume și prenume<input name="name" required autoComplete="name" defaultValue={account?.displayName||""} readOnly={Boolean(account)} /></label><label>Adresă de e-mail<input name="email" type="email" required autoComplete="email" defaultValue={account?.email||""} readOnly={Boolean(account)} /></label><label>Titlul trimiterii<input name="title" required placeholder={kind === "business" ? "Numele afacerii" : "Titlu scurt și clar"} /></label><div className="form-row"><label>Localitate<select name="locality"><option>Blaj</option><option>Sâncel</option><option>Jidvei</option><option>Valea Lungă</option><option>Altă localitate</option></select></label><label>Categorie<select name="category"><option>Comunitate</option><option>Servicii</option><option>Cultură</option><option>Gastronomie</option><option>Locuri de muncă</option><option>Altă categorie</option></select></label></div><label>Descriere<textarea name="description" required rows={6} placeholder="Include informațiile esențiale și orice condiții importante." /></label><label>Sursă sau pagină oficială<input name="source" type="url" placeholder="https://" /></label>{kind === "contribution" && <label className="file-field"><Upload /><span>Fotografie (JPG, PNG sau WebP, maximum 8 MB)</span><input name="media" type="file" accept="image/jpeg,image/png,image/webp" /></label>}<label className="consent"><input type="checkbox" name="rights" required /> Confirm că informația este corectă și că am dreptul să trimit acest conținut.</label><label className="consent"><input type="checkbox" name="consent" required /> Sunt de acord cu prelucrarea datelor pentru verificarea și administrarea trimiterii.</label><div className="moderation-note"><ShieldCheck /><p><strong>Publicare doar după moderare.</strong> Trimiterea începe cu starea „În așteptarea verificării”.</p></div><button className="button" disabled={state === "sending"}>{state === "sending" ? "Se trimite…" : "Trimite spre verificare"} <ArrowRight /></button>{state === "error" && <p className="error-message">Nu am putut înregistra trimiterea. Verifică datele și încearcă din nou.</p>}</form><aside className="form-aside"><span>01</span><h3>Date clare</h3><p>Scrie simplu, fără promisiuni exagerate. Nu include date personale inutile.</p><span>02</span><h3>Surse la vedere</h3><p>Adaugă pagina oficială sau o persoană de contact pentru verificare.</p><span>03</span><h3>Control editorial</h3><p>Administratorul poate aproba, respinge sau solicita modificări.</p></aside></section>;
}

export function StaticPage({ slug }: { slug: string }) {
  const pages: Record<string, [string, string, string[]]> = {
    despre: ["Despre Blaj Azi", "Un ghid local independent, construit pentru a face informația din Blaj mai ușor de găsit și de verificat.", ["Punem utilitatea înaintea zgomotului.", "Marcăm vizibil conținutul demonstrativ și promovarea plătită.", "Corectăm informația atunci când comunitatea ne semnalează o problemă."]],
    confidentialitate: ["Politica de confidențialitate", "Colectăm doar datele necesare pentru înscrieri, trimiteri și mesaje.", ["Datele din formulare sunt folosite pentru verificare și răspuns.", "Consimțământul de marketing nu este preselectat.", "Poți solicita accesul, corectarea sau ștergerea datelor prin pagina de contact."]],
    "cookie-uri": ["Politica privind cookie-urile", "Folosim doar elementele tehnice necesare funcționării. Analiza opțională va fi activată numai după consimțământ.", ["Nu folosim cookie-uri publicitare în această versiune.", "Preferințele locale nu devin sursă de date publice.", "Orice instrument viitor va fi documentat înainte de activare."]],
    termeni: ["Termeni și condiții", "Blaj Azi oferă un ghid informativ. Informațiile dependente de timp trebuie confirmate la sursa indicată.", ["Trimiterile utilizatorilor sunt moderate înainte de publicare.", "Conținutul plătit este etichetat clar.", "Materialele media păstrează sursa, autorul și licența."]],
  };
  const [title, intro, points] = pages[slug];
  return <><PageHero eyebrow="Blaj Azi" title={title} intro={intro} /><section className="container prose-page">{points.map((p, i) => <article key={p}><span>0{i + 1}</span><p>{p}</p></article>)}<p className="last-update">Ultima actualizare: 8 august 2026</p></section></>;
}

export function SearchPage({ initial = "",catalog }: { initial?: string;catalog:PublicCatalog }) {
  const {events,businesses,restaurants,jobs,places,posts}=catalog;const [q, setQ] = useState(initial); const normalize = (s: string) => s.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase(); const pool = [...events.map(x => ({...x, section:"evenimente"})), ...businesses.map(x => ({...x, section:"afaceri-si-servicii"})), ...restaurants.map(x => ({...x, section:"unde-mancam"})), ...jobs.map(x => ({...x, section:"locuri-de-munca"})), ...places.map(x => ({...x, section:"descopera-blaj"})),...posts.map(x=>({...x,section:"povesti-locale"}))]; const results = q ? pool.filter(x => normalize(JSON.stringify(x)).includes(normalize(q))) : [];
  return <><PageHero eyebrow="Căutare globală" title="Ce cauți în Blaj?" intro="Căutarea recunoaște termenii scriși cu sau fără diacritice." /><section className="container search-page"><label><Search /><input value={q} onInput={e => setQ(e.currentTarget.value)} placeholder="Exemplu: restaurant, electrician, copii" /></label>{q && <p>{results.length} rezultate pentru „{q}”</p>}<div className="generic-list">{results.map((x, i) => <GenericResult key={`${x.section}-${x.id}`} slug={x.section} item={x} index={i} />)}</div>{q && results.length === 0 && <div className="empty-state"><Search /><h3>Nu am găsit „{q}”.</h3><p>Încearcă „restaurant”, „copii”, „Blaj” sau o categorie apropiată.</p></div>}</section></>;
}

function PageHero({ eyebrow, title, intro }: { eyebrow: string; title: string; intro: string }) { return <section className="page-hero"><div className="container"><nav className="breadcrumbs" aria-label="Fir de navigare"><Link href="/">Acasă</Link><ChevronRight /><span>{title}</span></nav><p className="kicker">{eyebrow}</p><h1>{title}</h1><p>{intro}</p></div></section>; }
function formatPublicDate(value?:string){if(!value)return "Data nu este disponibilă";const normalized=/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/.test(value)?`${value.replace(" ","T")}Z`:value;const parsed=new Date(normalized);return Number.isNaN(parsed.getTime())?"Data nu este disponibilă":new Intl.DateTimeFormat("ro-RO",{dateStyle:"long"}).format(parsed)}
