import { integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";

const audit = {
  status: text("status").notNull().default("draft"),
  sourceUrl: text("source_url"),
  lastVerifiedAt: text("last_verified_at"),
  createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP"),
  updatedAt: text("updated_at").notNull().default("CURRENT_TIMESTAMP"),
};

export const categories = sqliteTable("categories", { id: integer("id").primaryKey({ autoIncrement: true }), name: text("name").notNull(), slug: text("slug").notNull().unique(), type: text("type").notNull() });
export const businesses = sqliteTable("businesses", { id: integer("id").primaryKey({ autoIncrement: true }), name: text("name").notNull(), slug: text("slug").notNull().unique(), categoryId: integer("category_id"), locality: text("locality").notNull(), address: text("address"), latitude: real("latitude"), longitude: real("longitude"), phone: text("phone"), website: text("website"), description: text("description"), verified: integer("verified", { mode: "boolean" }).notNull().default(false), ...audit });
export const businessHours = sqliteTable("business_hours", { id: integer("id").primaryKey({ autoIncrement: true }), businessId: integer("business_id").notNull(), weekday: integer("weekday").notNull(), opensAt: text("opens_at"), closesAt: text("closes_at"), closed: integer("closed", { mode: "boolean" }).notNull().default(false) });
export const events = sqliteTable("events", { id: integer("id").primaryKey({ autoIncrement: true }), title: text("title").notNull(), slug: text("slug").notNull().unique(), categoryId: integer("category_id"), organizer: text("organizer"), locality: text("locality").notNull(), venue: text("venue"), startsAt: text("starts_at").notNull(), endsAt: text("ends_at"), ticketInfo: text("ticket_info"), description: text("description"), ...audit });
export const offers = sqliteTable("offers", { id: integer("id").primaryKey({ autoIncrement: true }), businessId: integer("business_id"), title: text("title").notNull(), slug: text("slug").notNull().unique(), startsAt: text("starts_at").notNull(), endsAt: text("ends_at").notNull(), price: real("price"), oldPrice: real("old_price"), terms: text("terms"), ...audit });
export const restaurants = sqliteTable("restaurants", { id: integer("id").primaryKey({ autoIncrement: true }), businessId: integer("business_id"), name: text("name").notNull(), slug: text("slug").notNull().unique(), cuisine: text("cuisine"), delivery: integer("delivery", { mode: "boolean" }).notNull().default(false), pickup: integer("pickup", { mode: "boolean" }).notNull().default(false), dietaryOptions: text("dietary_options"), ...audit });
export const dailyMenus = sqliteTable("daily_menus", { id: integer("id").primaryKey({ autoIncrement: true }), restaurantId: integer("restaurant_id").notNull(), menuDate: text("menu_date").notNull(), soup: text("soup"), mainDish: text("main_dish"), sideDish: text("side_dish"), dessert: text("dessert"), price: real("price"), orderDeadline: text("order_deadline"), availability: text("availability").notNull().default("active"), updatedAt: text("updated_at").notNull().default("CURRENT_TIMESTAMP") });
export const jobs = sqliteTable("jobs", { id: integer("id").primaryKey({ autoIncrement: true }), businessId: integer("business_id"), title: text("title").notNull(), slug: text("slug").notNull().unique(), company: text("company").notNull(), locality: text("locality").notNull(), contractType: text("contract_type"), schedule: text("schedule"), salaryMin: real("salary_min"), salaryMax: real("salary_max"), transportProvided: integer("transport_provided", { mode: "boolean" }).notNull().default(false), applyUrl: text("apply_url"), deadline: text("deadline"), ...audit });
export const places = sqliteTable("places", { id: integer("id").primaryKey({ autoIncrement: true }), title: text("title").notNull(), slug: text("slug").notNull().unique(), address: text("address"), description: text("description"), accessibility: text("accessibility"), ...audit });
export const articles = sqliteTable("articles", { id: integer("id").primaryKey({ autoIncrement: true }), title: text("title").notNull(), slug: text("slug").notNull().unique(), author: text("author"), body: text("body").notNull(), publishedAt: text("published_at"), ...audit });
export const mediaAssets = sqliteTable("media_assets", { id: integer("id").primaryKey({ autoIncrement: true }), r2Key: text("r2_key"), title: text("title"), description: text("description"), photographer: text("photographer"), sourceUrl: text("source_url"), license: text("license"), altText: text("alt_text"), location: text("location"), category: text("category"), featured: integer("featured", { mode: "boolean" }).notNull().default(false), createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP") });
export const submissions = sqliteTable("submissions", { id: integer("id").primaryKey({ autoIncrement: true }), type: text("type").notNull(), contributorName: text("contributor_name"), email: text("email").notNull(), title: text("title"), locality: text("locality"), category: text("category"), description: text("description"), sourceUrl: text("source_url"), mediaKey: text("media_key"), rightsConfirmed: integer("rights_confirmed", { mode: "boolean" }).notNull().default(false), consent: integer("consent", { mode: "boolean" }).notNull(), status: text("status").notNull().default("pending_review"), createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP") });
export const moderationRecords = sqliteTable("moderation_records", { id: integer("id").primaryKey({ autoIncrement: true }), submissionId: integer("submission_id").notNull(), moderatorId: text("moderator_id").notNull(), action: text("action").notNull(), note: text("note"), createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP") });
export const newsletterSubscriptions = sqliteTable("newsletter_subscriptions", { id: integer("id").primaryKey({ autoIncrement: true }), email: text("email").notNull().unique(), interests: text("interests"), consentAt: text("consent_at").notNull().default("CURRENT_TIMESTAMP"), status: text("status").notNull().default("pending_confirmation") });
export const promotedPlacements = sqliteTable("promoted_placements", { id: integer("id").primaryKey({ autoIncrement: true }), entityType: text("entity_type").notNull(), entityId: integer("entity_id").notNull(), tier: text("tier").notNull(), startsAt: text("starts_at").notNull(), endsAt: text("ends_at").notNull(), status: text("status").notNull().default("scheduled") });
export const contactMessages = sqliteTable("contact_messages", { id: integer("id").primaryKey({ autoIncrement: true }), name: text("name"), email: text("email").notNull(), message: text("message").notNull(), status: text("status").notNull().default("new"), createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP") });
export const contentReports = sqliteTable("content_reports", { id: integer("id").primaryKey({ autoIncrement: true }), entityType: text("entity_type"), entityId: integer("entity_id"), email: text("email"), reason: text("reason").notNull(), status: text("status").notNull().default("new"), createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP") });
